/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordertracker;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jori El-Saikali
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar_jPanel = new javax.swing.JPanel();
        home_jLabel = new javax.swing.JLabel();
        add_user_jLabel = new javax.swing.JLabel();
        complete_order_jLabel = new javax.swing.JLabel();
        calendar_jLabel = new javax.swing.JLabel();
        share_jLabel = new javax.swing.JLabel();
        toolbar_blank_jPanel = new javax.swing.JPanel();
        search_area_jPanel = new javax.swing.JPanel();
        search_icon_jLabel = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        staples_logo_jLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        title_jPanel = new javax.swing.JPanel();
        home_title_jPanel = new javax.swing.JPanel();
        welcome_jLabel = new javax.swing.JLabel();
        order_tracker_jLabel = new javax.swing.JLabel();
        add_user_title_jPanel = new javax.swing.JPanel();
        add_user_subtitle_jLabel = new javax.swing.JLabel();
        add_user_title_jLabel = new javax.swing.JLabel();
        complete_order_title_jPanel = new javax.swing.JPanel();
        complete_order_subtitle_jLabel1 = new javax.swing.JLabel();
        complete_order_title_jLabel1 = new javax.swing.JLabel();
        calendar_title_jPanel = new javax.swing.JPanel();
        calendar_subtitle_jLabel = new javax.swing.JLabel();
        calendar_title_jLabel = new javax.swing.JLabel();
        share_title_jPanel = new javax.swing.JPanel();
        share_subtitle_jLabel = new javax.swing.JLabel();
        share_title_jLabel = new javax.swing.JLabel();
        user_area_jPanel = new javax.swing.JPanel();
        home_user_area_jPanel = new javax.swing.JPanel();
        thumbs_up_jLabel = new javax.swing.JLabel();
        instructions_icon_jLabel = new javax.swing.JLabel();
        instructions_title_jLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        credits_title_jLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        credits_description_jLabel = new javax.swing.JLabel();
        instructions_description_jLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1029, 657));
        setPreferredSize(new java.awt.Dimension(1029, 657));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar_jPanel.setBackground(new java.awt.Color(104, 100, 100));
        toolbar_jPanel.setLayout(new java.awt.GridLayout(5, 1));

        home_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/house-black-silhouette-without-door.png"))); // NOI18N
        home_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(home_jLabel);

        add_user_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_user_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/new-user.png"))); // NOI18N
        add_user_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_user_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(add_user_jLabel);

        complete_order_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        complete_order_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/checked.png"))); // NOI18N
        complete_order_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complete_order_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(complete_order_jLabel);

        calendar_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendar_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/calendar.png"))); // NOI18N
        calendar_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendar_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(calendar_jLabel);

        share_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        share_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/local-network.png"))); // NOI18N
        share_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                share_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(share_jLabel);

        getContentPane().add(toolbar_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 460));

        toolbar_blank_jPanel.setBackground(new java.awt.Color(104, 100, 100));

        javax.swing.GroupLayout toolbar_blank_jPanelLayout = new javax.swing.GroupLayout(toolbar_blank_jPanel);
        toolbar_blank_jPanel.setLayout(toolbar_blank_jPanelLayout);
        toolbar_blank_jPanelLayout.setHorizontalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        toolbar_blank_jPanelLayout.setVerticalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(toolbar_blank_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 60, 210));

        search_area_jPanel.setBackground(new java.awt.Color(244, 237, 237));

        search_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/search.png"))); // NOI18N

        search_jTextField.setBackground(new java.awt.Color(0, 0, 0));
        search_jTextField.setBorder(null);
        search_jTextField.setOpaque(false);
        search_jTextField.setBackground(new Color(0,0,0,0));

        staples_logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/staples--english-french-logo-2.png"))); // NOI18N

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout search_area_jPanelLayout = new javax.swing.GroupLayout(search_area_jPanel);
        search_area_jPanel.setLayout(search_area_jPanelLayout);
        search_area_jPanelLayout.setHorizontalGroup(
            search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_area_jPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(search_icon_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search_jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(staples_logo_jLabel)
                .addGap(26, 26, 26))
            .addGroup(search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_area_jPanelLayout.createSequentialGroup()
                    .addContainerGap(884, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
        search_area_jPanelLayout.setVerticalGroup(
            search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_icon_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_area_jPanelLayout.createSequentialGroup()
                .addGroup(search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(search_area_jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, search_area_jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search_jTextField)
                            .addComponent(staples_logo_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(search_area_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_area_jPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(search_area_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 980, 50));

        title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        title_jPanel.setLayout(new java.awt.CardLayout());

        home_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        home_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcome_jLabel.setText("Welcome To");
        home_title_jPanel.add(welcome_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 258, -1));

        order_tracker_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        order_tracker_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        order_tracker_jLabel.setText("Order Tracker");
        home_title_jPanel.add(order_tracker_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, 537, -1));

        title_jPanel.add(home_title_jPanel, "card2");

        add_user_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        add_user_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        add_user_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_subtitle_jLabel.setText("Adding a customer's name to a specific time slot");
        add_user_title_jPanel.add(add_user_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        add_user_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        add_user_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_title_jLabel.setText("Add A Customer");
        add_user_title_jPanel.add(add_user_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(add_user_title_jPanel, "card2");

        complete_order_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        complete_order_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_subtitle_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        complete_order_subtitle_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_subtitle_jLabel1.setText("Complete an order on a specific time slot.");
        complete_order_title_jPanel.add(complete_order_subtitle_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        complete_order_title_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        complete_order_title_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_title_jLabel1.setText("Complete Order");
        complete_order_title_jPanel.add(complete_order_title_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(complete_order_title_jPanel, "card2");

        calendar_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        calendar_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calendar_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_subtitle_jLabel.setText("View all time slots for either today or tomorrow.");
        calendar_title_jPanel.add(calendar_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        calendar_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        calendar_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_title_jLabel.setText("Time Slots");
        calendar_title_jPanel.add(calendar_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(calendar_title_jPanel, "card2");

        share_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        share_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        share_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_subtitle_jLabel.setText("Share all time slot data with other Order Tracker's.");
        share_title_jPanel.add(share_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 820, -1));

        share_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        share_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_title_jLabel.setText("Share");
        share_title_jPanel.add(share_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(share_title_jPanel, "card2");

        getContentPane().add(title_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 980, 260));

        user_area_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        user_area_jPanel.setLayout(new java.awt.CardLayout());

        home_user_area_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        home_user_area_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thumbs_up_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thumbs_up_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/thumbs-up.png"))); // NOI18N
        home_user_area_jPanel.add(thumbs_up_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 88, -1, -1));

        instructions_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/instructions.png"))); // NOI18N
        home_user_area_jPanel.add(instructions_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 88, -1, -1));

        instructions_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instructions_title_jLabel.setText("Instructions");
        home_user_area_jPanel.add(instructions_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 170, -1, -1));
        home_user_area_jPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));
        home_user_area_jPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));

        credits_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        credits_title_jLabel.setText("Credits");
        home_user_area_jPanel.add(credits_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));
        home_user_area_jPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 190, 140, -1));

        credits_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits_description_jLabel.setText("<html><center>Credits given to those<br>who made Order Tracker<br>possible.</html>");
        credits_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_user_area_jPanel.add(credits_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        instructions_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_description_jLabel.setText("<html><center>Clear instrustions on how<br>to use Order Tracker.</html>");
        instructions_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_user_area_jPanel.add(instructions_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        home_user_area_jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 240));

        user_area_jPanel.add(home_user_area_jPanel, "card2");

        getContentPane().add(user_area_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 298, 980, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_jLabelMouseClicked
        title_jPanel.removeAll();
        title_jPanel.add(home_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_home_jLabelMouseClicked

    private void add_user_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_user_jLabelMouseClicked
        title_jPanel.removeAll();
        title_jPanel.add(add_user_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_add_user_jLabelMouseClicked

    private void complete_order_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complete_order_jLabelMouseClicked
        title_jPanel.removeAll();
        title_jPanel.add(complete_order_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_complete_order_jLabelMouseClicked

    private void calendar_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendar_jLabelMouseClicked
        title_jPanel.removeAll();
        title_jPanel.add(calendar_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_calendar_jLabelMouseClicked

    private void share_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_share_jLabelMouseClicked
        title_jPanel.removeAll();
        title_jPanel.add(share_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_share_jLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public void RunGFX() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_user_jLabel;
    private javax.swing.JLabel add_user_subtitle_jLabel;
    private javax.swing.JLabel add_user_title_jLabel;
    private javax.swing.JPanel add_user_title_jPanel;
    private javax.swing.JLabel calendar_jLabel;
    private javax.swing.JLabel calendar_subtitle_jLabel;
    private javax.swing.JLabel calendar_title_jLabel;
    private javax.swing.JPanel calendar_title_jPanel;
    private javax.swing.JLabel complete_order_jLabel;
    private javax.swing.JLabel complete_order_subtitle_jLabel1;
    private javax.swing.JLabel complete_order_title_jLabel1;
    private javax.swing.JPanel complete_order_title_jPanel;
    private javax.swing.JLabel credits_description_jLabel;
    private javax.swing.JLabel credits_title_jLabel;
    private javax.swing.JLabel home_jLabel;
    private javax.swing.JPanel home_title_jPanel;
    private javax.swing.JPanel home_user_area_jPanel;
    private javax.swing.JLabel instructions_description_jLabel;
    private javax.swing.JLabel instructions_icon_jLabel;
    private javax.swing.JLabel instructions_title_jLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel order_tracker_jLabel;
    private javax.swing.JPanel search_area_jPanel;
    private javax.swing.JLabel search_icon_jLabel;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JLabel share_jLabel;
    private javax.swing.JLabel share_subtitle_jLabel;
    private javax.swing.JLabel share_title_jLabel;
    private javax.swing.JPanel share_title_jPanel;
    private javax.swing.JLabel staples_logo_jLabel;
    private javax.swing.JLabel thumbs_up_jLabel;
    private javax.swing.JPanel title_jPanel;
    private javax.swing.JPanel toolbar_blank_jPanel;
    private javax.swing.JPanel toolbar_jPanel;
    private javax.swing.JPanel user_area_jPanel;
    private javax.swing.JLabel welcome_jLabel;
    // End of variables declaration//GEN-END:variables
}
