/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordertracker;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Jori El-Saikali
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocation(300,100);
        initialize();
    }

    private void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("verified-notes-symbol.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        toolbar_jPanel = new javax.swing.JPanel();
        home_jLabel = new javax.swing.JLabel();
        add_user_jLabel = new javax.swing.JLabel();
        complete_order_jLabel = new javax.swing.JLabel();
        calendar_jLabel = new javax.swing.JLabel();
        share_jLabel = new javax.swing.JLabel();
        toolbar_blank_jPanel = new javax.swing.JPanel();
        search_area_jPanel = new javax.swing.JPanel();
        search_icon_jLabel = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        staples_logo_jLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        title_jPanel = new javax.swing.JPanel();
        home_title_jPanel = new javax.swing.JPanel();
        welcome_jLabel = new javax.swing.JLabel();
        order_tracker_jLabel = new javax.swing.JLabel();
        add_user_title_jPanel = new javax.swing.JPanel();
        add_user_subtitle_jLabel = new javax.swing.JLabel();
        add_user_title_jLabel = new javax.swing.JLabel();
        complete_order_title_jPanel = new javax.swing.JPanel();
        complete_order_subtitle_jLabel1 = new javax.swing.JLabel();
        complete_order_title_jLabel1 = new javax.swing.JLabel();
        calendar_title_jPanel = new javax.swing.JPanel();
        calendar_subtitle_jLabel = new javax.swing.JLabel();
        calendar_title_jLabel = new javax.swing.JLabel();
        share_title_jPanel = new javax.swing.JPanel();
        share_subtitle_jLabel = new javax.swing.JLabel();
        share_title_jLabel = new javax.swing.JLabel();
        UI_jPanel = new javax.swing.JPanel();
        home_UI_jPanel = new javax.swing.JPanel();
        thumbs_up_jLabel = new javax.swing.JLabel();
        instructions_icon_jLabel = new javax.swing.JLabel();
        instructions_title_jLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        credits_title_jLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        credits_description_jLabel = new javax.swing.JLabel();
        instructions_description_jLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        share_UI_jPanel = new javax.swing.JPanel();
        add_user_UI_jPanel = new javax.swing.JPanel();
        add_user_TS_jLabel = new javax.swing.JLabel();
        add_user_CN_jLabel = new javax.swing.JLabel();
        add_user_TT_jLabel = new javax.swing.JLabel();
        add_user_CN_jTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        add_user_TT_jComboBox = new javax.swing.JComboBox<>();
        add_user_TS_jComboBox = new javax.swing.JComboBox<>();
        complete_order_UI_jPanel = new javax.swing.JPanel();
        complete_order_CN_jLabel = new javax.swing.JLabel();
        complete_order_CN_jTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        complete_order_TS_jLabel = new javax.swing.JLabel();
        complete_order_TS_jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        calendar_UI_jPanel = new javax.swing.JPanel();
        calendar_TT_jLabel = new javax.swing.JLabel();
        calendar_TT_jComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OrderTracker");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1029, 657));
        setName("main_frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1029, 657));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar_jPanel.setBackground(new java.awt.Color(104, 100, 100));
        toolbar_jPanel.setLayout(new java.awt.GridLayout(5, 1));

        home_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/house-black-silhouette-without-door.png"))); // NOI18N
        home_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(home_jLabel);

        add_user_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_user_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/new-user.png"))); // NOI18N
        add_user_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_user_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(add_user_jLabel);

        complete_order_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        complete_order_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/checked.png"))); // NOI18N
        complete_order_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complete_order_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(complete_order_jLabel);

        calendar_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendar_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/calendar.png"))); // NOI18N
        calendar_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendar_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(calendar_jLabel);

        share_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        share_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/local-network.png"))); // NOI18N
        share_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                share_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(share_jLabel);

        getContentPane().add(toolbar_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 460));

        toolbar_blank_jPanel.setBackground(new java.awt.Color(104, 100, 100));

        javax.swing.GroupLayout toolbar_blank_jPanelLayout = new javax.swing.GroupLayout(toolbar_blank_jPanel);
        toolbar_blank_jPanel.setLayout(toolbar_blank_jPanelLayout);
        toolbar_blank_jPanelLayout.setHorizontalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        toolbar_blank_jPanelLayout.setVerticalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(toolbar_blank_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 60, 210));

        search_area_jPanel.setBackground(new java.awt.Color(244, 237, 237));
        search_area_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/search.png"))); // NOI18N
        search_area_jPanel.add(search_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 48, 50));

        search_jTextField.setBackground(new java.awt.Color(0, 0, 0));
        search_jTextField.setBorder(null);
        search_jTextField.setOpaque(false);
        search_jTextField.setBackground(new Color(0,0,0,0));
        search_area_jPanel.add(search_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, 531, 28));
        search_area_jPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, 531, -1));

        staples_logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/staples--english-french-logo-2.png"))); // NOI18N
        search_area_jPanel.add(staples_logo_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 11, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        search_area_jPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 12, -1, 24));

        getContentPane().add(search_area_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 980, 50));

        title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        title_jPanel.setLayout(new java.awt.CardLayout());

        home_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        home_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcome_jLabel.setText("Welcome To");
        home_title_jPanel.add(welcome_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 258, -1));

        order_tracker_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        order_tracker_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        order_tracker_jLabel.setText("Order Tracker");
        home_title_jPanel.add(order_tracker_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, 537, -1));

        title_jPanel.add(home_title_jPanel, "card2");

        add_user_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        add_user_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        add_user_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_subtitle_jLabel.setText("Adding a customer's name to a specific time slot");
        add_user_title_jPanel.add(add_user_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        add_user_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        add_user_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_title_jLabel.setText("Add A Customer");
        add_user_title_jPanel.add(add_user_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(add_user_title_jPanel, "card2");

        complete_order_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        complete_order_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_subtitle_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        complete_order_subtitle_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_subtitle_jLabel1.setText("Remove finished orders at a specific time slot.");
        complete_order_title_jPanel.add(complete_order_subtitle_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        complete_order_title_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        complete_order_title_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_title_jLabel1.setText("Complete Order");
        complete_order_title_jPanel.add(complete_order_title_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(complete_order_title_jPanel, "card2");

        calendar_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        calendar_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calendar_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_subtitle_jLabel.setText("View all time slots for either today or tomorrow.");
        calendar_title_jPanel.add(calendar_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        calendar_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        calendar_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_title_jLabel.setText("Time Slots");
        calendar_title_jPanel.add(calendar_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(calendar_title_jPanel, "card2");

        share_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        share_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        share_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_subtitle_jLabel.setText("Share time slot data with other local Order Trackers.");
        share_title_jPanel.add(share_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 850, -1));

        share_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        share_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_title_jLabel.setText("Share");
        share_title_jPanel.add(share_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(share_title_jPanel, "card2");

        getContentPane().add(title_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 980, 260));

        UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        UI_jPanel.setLayout(new java.awt.CardLayout());

        home_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        home_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thumbs_up_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thumbs_up_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/thumbs-up.png"))); // NOI18N
        home_UI_jPanel.add(thumbs_up_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 88, -1, -1));

        instructions_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ordertracker/instructions.png"))); // NOI18N
        home_UI_jPanel.add(instructions_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 88, -1, -1));

        instructions_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instructions_title_jLabel.setText("Instructions");
        home_UI_jPanel.add(instructions_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 170, -1, -1));
        home_UI_jPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));
        home_UI_jPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));

        credits_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        credits_title_jLabel.setText("Credits");
        home_UI_jPanel.add(credits_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));
        home_UI_jPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 190, 140, -1));

        credits_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits_description_jLabel.setText("<html><center>Credits given to those<br>who made Order Tracker<br>possible.</html>");
        credits_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(credits_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        instructions_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_description_jLabel.setText("<html><center>Clear instrustions on how<br>to use Order Tracker.</html>");
        instructions_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(instructions_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        home_UI_jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 240));

        UI_jPanel.add(home_UI_jPanel, "card2");

        share_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        share_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        UI_jPanel.add(share_UI_jPanel, "card2");

        add_user_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        add_user_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TS_jLabel.setText("Time Slot:");
        add_user_UI_jPanel.add(add_user_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        add_user_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jLabel.setText("Customer's Name:");
        add_user_UI_jPanel.add(add_user_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        add_user_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TT_jLabel.setText("Today/Tomorrow:");
        add_user_UI_jPanel.add(add_user_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 128, -1, -1));

        add_user_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jTextField.setBorder(null);
        add_user_CN_jTextField.setOpaque(false);
        add_user_CN_jTextField.setBackground(new Color(0,0,0,0));

        add_user_CN_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_CN_jTextFieldActionPerformed(evt);
            }
        });
        add_user_UI_jPanel.add(add_user_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 66, 340, 30));
        add_user_UI_jPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 96, 340, -1));

        add_user_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        add_user_UI_jPanel.add(add_user_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        add_user_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30  PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        add_user_UI_jPanel.add(add_user_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, -1));

        UI_jPanel.add(add_user_UI_jPanel, "card2");

        complete_order_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        complete_order_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jLabel.setText("Customer's Name:");
        complete_order_UI_jPanel.add(complete_order_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        complete_order_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jTextField.setBorder(null);
        complete_order_CN_jTextField.setOpaque(false);
        complete_order_CN_jTextField.setBackground(new Color(0,0,0,0));
        complete_order_CN_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_order_CN_jTextFieldActionPerformed(evt);
            }
        });
        complete_order_UI_jPanel.add(complete_order_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 340, 30));
        complete_order_UI_jPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 340, -1));

        complete_order_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_TS_jLabel.setText("Time Slot:");
        complete_order_UI_jPanel.add(complete_order_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        complete_order_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30  PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        complete_order_UI_jPanel.add(complete_order_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html>Need help finding a customer's name?<br>Search by time slot!</html>");
        complete_order_UI_jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        UI_jPanel.add(complete_order_UI_jPanel, "card2");

        calendar_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        calendar_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calendar_TT_jLabel.setText("Today/Tomorrow:");
        calendar_UI_jPanel.add(calendar_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        calendar_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        calendar_UI_jPanel.add(calendar_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 170, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        calendar_UI_jPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 860, 210));

        UI_jPanel.add(calendar_UI_jPanel, "card2");

        getContentPane().add(UI_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 970, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(home_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(home_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_home_jLabelMouseClicked

    private void add_user_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_user_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(add_user_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(add_user_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_add_user_jLabelMouseClicked

    private void complete_order_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complete_order_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(complete_order_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(complete_order_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_complete_order_jLabelMouseClicked

    private void calendar_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendar_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(calendar_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(calendar_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_calendar_jLabelMouseClicked

    private void share_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_share_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(share_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(share_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_share_jLabelMouseClicked

    private void add_user_CN_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_CN_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_user_CN_jTextFieldActionPerformed

    private void complete_order_CN_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_order_CN_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complete_order_CN_jTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void RunGFX() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UI_jPanel;
    private javax.swing.JLabel add_user_CN_jLabel;
    private javax.swing.JTextField add_user_CN_jTextField;
    private javax.swing.JComboBox<String> add_user_TS_jComboBox;
    private javax.swing.JLabel add_user_TS_jLabel;
    private javax.swing.JComboBox<String> add_user_TT_jComboBox;
    private javax.swing.JLabel add_user_TT_jLabel;
    private javax.swing.JPanel add_user_UI_jPanel;
    private javax.swing.JLabel add_user_jLabel;
    private javax.swing.JLabel add_user_subtitle_jLabel;
    private javax.swing.JLabel add_user_title_jLabel;
    private javax.swing.JPanel add_user_title_jPanel;
    private javax.swing.JComboBox<String> calendar_TT_jComboBox;
    private javax.swing.JLabel calendar_TT_jLabel;
    private javax.swing.JPanel calendar_UI_jPanel;
    private javax.swing.JLabel calendar_jLabel;
    private javax.swing.JLabel calendar_subtitle_jLabel;
    private javax.swing.JLabel calendar_title_jLabel;
    private javax.swing.JPanel calendar_title_jPanel;
    private javax.swing.JLabel complete_order_CN_jLabel;
    private javax.swing.JTextField complete_order_CN_jTextField;
    private javax.swing.JComboBox<String> complete_order_TS_jComboBox;
    private javax.swing.JLabel complete_order_TS_jLabel;
    private javax.swing.JPanel complete_order_UI_jPanel;
    private javax.swing.JLabel complete_order_jLabel;
    private javax.swing.JLabel complete_order_subtitle_jLabel1;
    private javax.swing.JLabel complete_order_title_jLabel1;
    private javax.swing.JPanel complete_order_title_jPanel;
    private javax.swing.JLabel credits_description_jLabel;
    private javax.swing.JLabel credits_title_jLabel;
    private javax.swing.JPanel home_UI_jPanel;
    private javax.swing.JLabel home_jLabel;
    private javax.swing.JPanel home_title_jPanel;
    private javax.swing.JLabel instructions_description_jLabel;
    private javax.swing.JLabel instructions_icon_jLabel;
    private javax.swing.JLabel instructions_title_jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel order_tracker_jLabel;
    private javax.swing.JPanel search_area_jPanel;
    private javax.swing.JLabel search_icon_jLabel;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JPanel share_UI_jPanel;
    private javax.swing.JLabel share_jLabel;
    private javax.swing.JLabel share_subtitle_jLabel;
    private javax.swing.JLabel share_title_jLabel;
    private javax.swing.JPanel share_title_jPanel;
    private javax.swing.JLabel staples_logo_jLabel;
    private javax.swing.JLabel thumbs_up_jLabel;
    private javax.swing.JPanel title_jPanel;
    private javax.swing.JPanel toolbar_blank_jPanel;
    private javax.swing.JPanel toolbar_jPanel;
    private javax.swing.JLabel welcome_jLabel;
    // End of variables declaration//GEN-END:variables
}
