/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordertracker;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Jori El-Saikali
 */
public class OrderTrackerView extends javax.swing.JFrame {

    private final OrderTrackerModel model;
    
    /**
     * Creates new form Home
     * @param m
     */
    public OrderTrackerView(OrderTrackerModel m) {
        this.model = m;
        initComponents();
        initialize();
    }

    private void initialize() {
        this.setLocation(300,100);
        this.setSize(1029, 657);
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/verified-notes-symbol.png")));
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                try {
                    model.writePersistantData();
                } catch (FileNotFoundException | UnsupportedEncodingException ex) {
                    displayError(ex.toString());
                } catch (IOException ex) {
                    displayError(ex.toString());
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolbar_jPanel = new javax.swing.JPanel();
        toolbar_home_jButton = new javax.swing.JButton();
        toolbar_add_user_jButton = new javax.swing.JButton();
        toolbar_complete_order_jButton = new javax.swing.JButton();
        toolbar_calendar_jButton = new javax.swing.JButton();
        toolbar_shift_jButton = new javax.swing.JButton();
        toolbar_share_jButton = new javax.swing.JButton();
        toolbar_settings_jButton = new javax.swing.JButton();
        toolbar_support_jPanel = new javax.swing.JPanel();
        toolbar_support_jButton = new javax.swing.JButton();
        toolbar_blank_jPanel = new javax.swing.JPanel();
        search_area_jPanel = new javax.swing.JPanel();
        search_icon_jLabel = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        staples_logo_jLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        title_jPanel = new javax.swing.JPanel();
        home_title_jPanel = new javax.swing.JPanel();
        welcome_jLabel = new javax.swing.JLabel();
        order_tracker_jLabel = new javax.swing.JLabel();
        add_user_title_jPanel = new javax.swing.JPanel();
        add_user_subtitle_jLabel = new javax.swing.JLabel();
        add_user_title_jLabel = new javax.swing.JLabel();
        complete_order_title_jPanel = new javax.swing.JPanel();
        complete_order_subtitle_jLabel1 = new javax.swing.JLabel();
        complete_order_title_jLabel1 = new javax.swing.JLabel();
        calendar_title_jPanel = new javax.swing.JPanel();
        calendar_subtitle_jLabel = new javax.swing.JLabel();
        calendar_title_jLabel = new javax.swing.JLabel();
        share_title_jPanel = new javax.swing.JPanel();
        share_subtitle_jLabel = new javax.swing.JLabel();
        share_title_jLabel = new javax.swing.JLabel();
        shift_title_jPanel = new javax.swing.JPanel();
        shift_subtitle_jLabel = new javax.swing.JLabel();
        shift_main_title_jLabel = new javax.swing.JLabel();
        instructions_title_jPanel = new javax.swing.JPanel();
        instructions_subtitle_jLabel = new javax.swing.JLabel();
        instructions_main_title_jLabel = new javax.swing.JLabel();
        credits_title_jPanel = new javax.swing.JPanel();
        credits_subtitle_jLabel = new javax.swing.JLabel();
        credits_main_title_jLabel = new javax.swing.JLabel();
        search_title_jPanel = new javax.swing.JPanel();
        search_subtitle_jLabel = new javax.swing.JLabel();
        search_main_title_jLabel = new javax.swing.JLabel();
        settings_title_jPanel = new javax.swing.JPanel();
        search_subtitle_jLabel1 = new javax.swing.JLabel();
        search_main_title_jLabel1 = new javax.swing.JLabel();
        UI_jPanel = new javax.swing.JPanel();
        home_UI_jPanel = new javax.swing.JPanel();
        instructions_title_jLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        credits_title_jLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        credits_description_jLabel = new javax.swing.JLabel();
        instructions_description_jLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        home_instructions_jButton = new javax.swing.JButton();
        home_credits_jButton = new javax.swing.JButton();
        complete_order_UI_jPanel = new javax.swing.JPanel();
        complete_order_CN_jLabel = new javax.swing.JLabel();
        complete_order_CN_jTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        complete_order_TT_jLabel = new javax.swing.JLabel();
        complete_order_TS_jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        complete_order_jScrollPane = new javax.swing.JScrollPane();
        complete_order_CN_jTable = new javax.swing.JTable();
        complete_order_TS_jLabel = new javax.swing.JLabel();
        complete_order_TT_jComboBox = new javax.swing.JComboBox<>();
        complete_order_submit_jButton = new javax.swing.JButton();
        calendar_UI_jPanel = new javax.swing.JPanel();
        calendar_TT_jLabel = new javax.swing.JLabel();
        calendar_TT_jComboBox = new javax.swing.JComboBox<>();
        calendar_jScrollPane = new javax.swing.JScrollPane();
        calendar_jTable = new javax.swing.JTable();
        share_UI_jPanel = new javax.swing.JPanel();
        share_body_title_jLabel = new javax.swing.JLabel();
        share_body_description_jLabel = new javax.swing.JLabel();
        share_submit_jButton = new javax.swing.JButton();
        instructions_UI_jPanel = new javax.swing.JPanel();
        instructions_howto_jLabel = new javax.swing.JLabel();
        instructions_questions_jComboBox = new javax.swing.JComboBox<>();
        instructions_body_jPanel = new javax.swing.JPanel();
        instructions_add_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel = new javax.swing.JLabel();
        instructions_body_answer_jLabel = new javax.swing.JLabel();
        instructions_add_user_icon_jLabel = new javax.swing.JLabel();
        instructions_add_user_tip_jLabel = new javax.swing.JLabel();
        instructions_add_user_tipbody_jLabel = new javax.swing.JLabel();
        instructions_complete_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel2 = new javax.swing.JLabel();
        instructions_body_answer_jLabel2 = new javax.swing.JLabel();
        instructions_complete_order_icon_jLabel = new javax.swing.JLabel();
        instructions_complete_order_tip_jLabel = new javax.swing.JLabel();
        instructions_complete_order_tipbody_jLabel = new javax.swing.JLabel();
        instructions_view_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel3 = new javax.swing.JLabel();
        instructions_body_answer_jLabel3 = new javax.swing.JLabel();
        instructions_view_icon_jLabel = new javax.swing.JLabel();
        instructions_share_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel4 = new javax.swing.JLabel();
        instructions_body_answer_jLabel4 = new javax.swing.JLabel();
        instructions_share_icon_jLabel = new javax.swing.JLabel();
        instructions_shift_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel7 = new javax.swing.JLabel();
        instructions_body_answer_jLabel7 = new javax.swing.JLabel();
        instructions_shift_icon_jLabel = new javax.swing.JLabel();
        instructions_dkcn_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel5 = new javax.swing.JLabel();
        instructions_body_answer_jLabel5 = new javax.swing.JLabel();
        instructions_max_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel6 = new javax.swing.JLabel();
        instructions_body_answer_jLabel6 = new javax.swing.JLabel();
        credits_UI_jPanel = new javax.swing.JPanel();
        credits_jScrollPane = new javax.swing.JScrollPane();
        credits_jTextArea = new javax.swing.JTextArea();
        add_user_UI_jPanel = new javax.swing.JPanel();
        add_user_TS_jLabel = new javax.swing.JLabel();
        add_user_CN_jLabel = new javax.swing.JLabel();
        add_user_TT_jLabel = new javax.swing.JLabel();
        add_user_CN_jTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        add_user_TT_jComboBox = new javax.swing.JComboBox<>();
        add_user_TS_jComboBox = new javax.swing.JComboBox<>();
        add_user_submit_jButton = new javax.swing.JButton();
        shift_UI_jPanel = new javax.swing.JPanel();
        shift_body_title_jLabel = new javax.swing.JLabel();
        shift_body_description_jLabel = new javax.swing.JLabel();
        shift_submit_jButton = new javax.swing.JButton();
        settings_UI_jPanel = new javax.swing.JPanel();
        settings_submit_jButton = new javax.swing.JButton();
        settings_path_jLabel = new javax.swing.JLabel();
        settings_max_jComboBox = new javax.swing.JComboBox<>();
        settings_max_jLabel = new javax.swing.JLabel();
        settings_path_jTextField = new javax.swing.JTextField();
        settings_file_chooser_jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("OrderTracker");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1029, 657));
        setName("main_frame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar_jPanel.setBackground(new java.awt.Color(104, 100, 100));
        toolbar_jPanel.setLayout(new java.awt.GridLayout(7, 1));

        toolbar_home_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_home_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/house-black-silhouette-without-door.png"))); // NOI18N
        toolbar_home_jButton.setToolTipText("Home");
        toolbar_home_jButton.setBorder(null);
        toolbar_home_jButton.setBorderPainted(false);
        toolbar_home_jButton.setContentAreaFilled(false);
        toolbar_home_jButton.setFocusPainted(false);
        toolbar_home_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_home_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_home_jButton);

        toolbar_add_user_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_add_user_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new-user.png"))); // NOI18N
        toolbar_add_user_jButton.setToolTipText("Add Customer");
        toolbar_add_user_jButton.setBorder(null);
        toolbar_add_user_jButton.setBorderPainted(false);
        toolbar_add_user_jButton.setContentAreaFilled(false);
        toolbar_add_user_jButton.setFocusPainted(false);
        toolbar_add_user_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_add_user_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_add_user_jButton);

        toolbar_complete_order_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_complete_order_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checked.png"))); // NOI18N
        toolbar_complete_order_jButton.setToolTipText("Complete Order");
        toolbar_complete_order_jButton.setBorder(null);
        toolbar_complete_order_jButton.setBorderPainted(false);
        toolbar_complete_order_jButton.setContentAreaFilled(false);
        toolbar_complete_order_jButton.setFocusPainted(false);
        toolbar_complete_order_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_complete_order_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_complete_order_jButton);

        toolbar_calendar_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_calendar_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calendar.png"))); // NOI18N
        toolbar_calendar_jButton.setToolTipText("View Time Slots");
        toolbar_calendar_jButton.setBorder(null);
        toolbar_calendar_jButton.setBorderPainted(false);
        toolbar_calendar_jButton.setContentAreaFilled(false);
        toolbar_calendar_jButton.setFocusPainted(false);
        toolbar_calendar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_calendar_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_calendar_jButton);

        toolbar_shift_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_shift_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shift-keyboard-key.png"))); // NOI18N
        toolbar_shift_jButton.setToolTipText("Shift Orders");
        toolbar_shift_jButton.setBorder(null);
        toolbar_shift_jButton.setBorderPainted(false);
        toolbar_shift_jButton.setContentAreaFilled(false);
        toolbar_shift_jButton.setFocusPainted(false);
        toolbar_shift_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_shift_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_shift_jButton);

        toolbar_share_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_share_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/local-network.png"))); // NOI18N
        toolbar_share_jButton.setToolTipText("Share");
        toolbar_share_jButton.setBorder(null);
        toolbar_share_jButton.setBorderPainted(false);
        toolbar_share_jButton.setContentAreaFilled(false);
        toolbar_share_jButton.setFocusPainted(false);
        toolbar_share_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_share_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_share_jButton);

        toolbar_settings_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_settings_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings-work-tool (2).png"))); // NOI18N
        toolbar_settings_jButton.setToolTipText("Home");
        toolbar_settings_jButton.setBorder(null);
        toolbar_settings_jButton.setBorderPainted(false);
        toolbar_settings_jButton.setContentAreaFilled(false);
        toolbar_settings_jButton.setFocusPainted(false);
        toolbar_settings_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_settings_jButtonActionPerformed(evt);
            }
        });
        toolbar_jPanel.add(toolbar_settings_jButton);

        getContentPane().add(toolbar_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 430));

        toolbar_support_jPanel.setBackground(new java.awt.Color(104, 100, 100));
        toolbar_support_jPanel.setLayout(new java.awt.GridLayout(1, 0));

        toolbar_support_jButton.setBackground(new java.awt.Color(192, 192, 192));
        toolbar_support_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/support.png"))); // NOI18N
        toolbar_support_jButton.setToolTipText("Contact developer at jorielsaikali@gmail.com");
        toolbar_support_jButton.setBorder(null);
        toolbar_support_jButton.setBorderPainted(false);
        toolbar_support_jButton.setContentAreaFilled(false);
        toolbar_support_jButton.setFocusPainted(false);
        toolbar_support_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolbar_support_jButtonActionPerformed(evt);
            }
        });
        toolbar_support_jButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent me) {
                ToolTipManager.sharedInstance().setInitialDelay(0);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                ToolTipManager.sharedInstance().setDismissDelay(ToolTipManager.sharedInstance().getDismissDelay());
            }
        });
        toolbar_support_jPanel.add(toolbar_support_jButton);

        getContentPane().add(toolbar_support_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 565, 60, 60));

        toolbar_blank_jPanel.setBackground(new java.awt.Color(104, 100, 100));

        javax.swing.GroupLayout toolbar_blank_jPanelLayout = new javax.swing.GroupLayout(toolbar_blank_jPanel);
        toolbar_blank_jPanel.setLayout(toolbar_blank_jPanelLayout);
        toolbar_blank_jPanelLayout.setHorizontalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        toolbar_blank_jPanelLayout.setVerticalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(toolbar_blank_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 60, 230));

        search_area_jPanel.setBackground(new java.awt.Color(244, 237, 237));
        search_area_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        search_area_jPanel.add(search_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 48, 50));

        search_jTextField.setBackground(new java.awt.Color(0, 0, 0));
        search_jTextField.setForeground(new java.awt.Color(102, 102, 102));
        search_jTextField.setText("Search a non-existing or existing customer name for quick addition or completion");
        search_jTextField.setBorder(null);
        search_jTextField.setOpaque(false);
        search_jTextField.setBackground(new Color(0,0,0,0));
        search_jTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_jTextFieldMouseClicked(evt);
            }
        });
        search_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_jTextFieldKeyPressed(evt);
            }
        });
        search_area_jPanel.add(search_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, 531, 28));
        search_area_jPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, 531, -1));

        staples_logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/staples--english-french-logo-2.png"))); // NOI18N
        search_area_jPanel.add(staples_logo_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 11, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        search_area_jPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 12, -1, 24));

        getContentPane().add(search_area_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 980, 50));

        title_jPanel.setBackground(new java.awt.Color(255, 255, 255));
        title_jPanel.setLayout(new java.awt.CardLayout());

        home_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        home_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcome_jLabel.setText("Welcome To");
        home_title_jPanel.add(welcome_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 258, -1));

        order_tracker_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        order_tracker_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        order_tracker_jLabel.setText("OrderTracker");
        home_title_jPanel.add(order_tracker_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, 537, -1));

        title_jPanel.add(home_title_jPanel, "card2");

        add_user_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        add_user_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        add_user_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_subtitle_jLabel.setText("Adding a customer's name to a specific time slot");
        add_user_title_jPanel.add(add_user_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        add_user_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        add_user_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_title_jLabel.setText("Add A Customer");
        add_user_title_jPanel.add(add_user_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(add_user_title_jPanel, "card2");

        complete_order_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        complete_order_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_subtitle_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        complete_order_subtitle_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_subtitle_jLabel1.setText("Remove finished orders at a specific time slot.");
        complete_order_title_jPanel.add(complete_order_subtitle_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        complete_order_title_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        complete_order_title_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_title_jLabel1.setText("Complete Order");
        complete_order_title_jPanel.add(complete_order_title_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(complete_order_title_jPanel, "card2");

        calendar_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        calendar_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calendar_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_subtitle_jLabel.setText("View all time slots for either today or tomorrow.");
        calendar_title_jPanel.add(calendar_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        calendar_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        calendar_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_title_jLabel.setText("Time Slots");
        calendar_title_jPanel.add(calendar_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(calendar_title_jPanel, "card2");

        share_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        share_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        share_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_subtitle_jLabel.setText("Share time slot data with other local OrderTrackers.");
        share_title_jPanel.add(share_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 850, -1));

        share_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        share_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_title_jLabel.setText("Share");
        share_title_jPanel.add(share_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(share_title_jPanel, "card2");

        shift_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        shift_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shift_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        shift_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        shift_subtitle_jLabel.setText("Shift orders in a press of a button");
        shift_title_jPanel.add(shift_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        shift_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        shift_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        shift_main_title_jLabel.setText("Shift Orders");
        shift_title_jPanel.add(shift_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(shift_title_jPanel, "card2");

        instructions_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        instructions_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        instructions_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructions_subtitle_jLabel.setText("Frequently Asked Questions and Advice");
        instructions_title_jPanel.add(instructions_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        instructions_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        instructions_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructions_main_title_jLabel.setText("Instructions");
        instructions_title_jPanel.add(instructions_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(instructions_title_jPanel, "card2");

        credits_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        credits_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        credits_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        credits_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        credits_subtitle_jLabel.setText("Thank you to all who made OrderTracker possible!");
        credits_title_jPanel.add(credits_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        credits_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        credits_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        credits_main_title_jLabel.setText("Credits");
        credits_title_jPanel.add(credits_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(credits_title_jPanel, "card2");

        search_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        search_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        search_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        search_subtitle_jLabel.setText("An easy way to find customers and other things!");
        search_title_jPanel.add(search_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        search_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        search_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        search_main_title_jLabel.setText("Search");
        search_title_jPanel.add(search_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(search_title_jPanel, "card2");

        settings_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        settings_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_subtitle_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        search_subtitle_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        search_subtitle_jLabel1.setText("Set OrderTracker to the way your liking");
        settings_title_jPanel.add(search_subtitle_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        search_main_title_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        search_main_title_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        search_main_title_jLabel1.setText("Settings");
        settings_title_jPanel.add(search_main_title_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(settings_title_jPanel, "card2");

        getContentPane().add(title_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 980, 260));

        UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        UI_jPanel.setLayout(new java.awt.CardLayout());

        home_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        home_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instructions_title_jLabel.setText("Instructions");
        home_UI_jPanel.add(instructions_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 170, -1, -1));
        home_UI_jPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));
        home_UI_jPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));

        credits_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        credits_title_jLabel.setText("Credits");
        home_UI_jPanel.add(credits_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));
        home_UI_jPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 190, 140, -1));

        credits_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits_description_jLabel.setText("<html><center>Credits given to those<br>who made OrderTracker<br>possible.</html>");
        credits_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(credits_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        instructions_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_description_jLabel.setText("<html><center>Clear instrustions on how<br>to use Order Tracker.</html>");
        instructions_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(instructions_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        home_UI_jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, 240));

        home_instructions_jButton.setBackground(new java.awt.Color(192, 192, 192));
        home_instructions_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/instructions.png"))); // NOI18N
        home_instructions_jButton.setBorder(null);
        home_instructions_jButton.setBorderPainted(false);
        home_instructions_jButton.setContentAreaFilled(false);
        home_instructions_jButton.setFocusPainted(false);
        home_instructions_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_instructions_jButtonActionPerformed(evt);
            }
        });
        home_UI_jPanel.add(home_instructions_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 84, 70, 70));

        home_credits_jButton.setBackground(new java.awt.Color(192, 192, 192));
        home_credits_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thumbs-up.png"))); // NOI18N
        home_credits_jButton.setBorder(null);
        home_credits_jButton.setBorderPainted(false);
        home_credits_jButton.setContentAreaFilled(false);
        home_credits_jButton.setFocusPainted(false);
        home_credits_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_credits_jButtonActionPerformed(evt);
            }
        });
        home_UI_jPanel.add(home_credits_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 84, 70, 70));

        UI_jPanel.add(home_UI_jPanel, "card2");

        complete_order_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        complete_order_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jLabel.setText("Customer's Name:");
        complete_order_UI_jPanel.add(complete_order_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        complete_order_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jTextField.setBorder(null);
        complete_order_CN_jTextField.setOpaque(false);
        complete_order_CN_jTextField.setBackground(new Color(0,0,0,0));
        complete_order_UI_jPanel.add(complete_order_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 340, 30));
        complete_order_UI_jPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 340, -1));

        complete_order_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_TT_jLabel.setText("Today/Tomorrow:");
        complete_order_UI_jPanel.add(complete_order_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        complete_order_TS_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        complete_order_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        complete_order_TS_jComboBox.setFocusable(false);
        complete_order_TS_jComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                complete_order_TS_jComboBoxItemStateChanged(evt);
            }
        });
        complete_order_UI_jPanel.add(complete_order_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html>Need help finding a customer's name?<br>Search by time slot!</html>");
        complete_order_UI_jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        complete_order_CN_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Customer Name", "Customer Name", "Customer Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        complete_order_CN_jTable.setFocusable(false);
        complete_order_CN_jTable.setRowSelectionAllowed(false);
        complete_order_CN_jTable.getTableHeader().setResizingAllowed(false);
        complete_order_CN_jTable.getTableHeader().setReorderingAllowed(false);
        complete_order_jScrollPane.setVisible(false);
        complete_order_CN_jTable.setVisible(false);
        complete_order_jScrollPane.setViewportView(complete_order_CN_jTable);

        complete_order_UI_jPanel.add(complete_order_jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 520, 39));

        complete_order_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_TS_jLabel.setText("Time Slot:");
        complete_order_UI_jPanel.add(complete_order_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        complete_order_TT_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        complete_order_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        complete_order_TT_jComboBox.setFocusable(false);
        complete_order_TT_jComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                complete_order_TT_jComboBoxItemStateChanged(evt);
            }
        });
        complete_order_UI_jPanel.add(complete_order_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 170, -1));

        complete_order_submit_jButton.setBackground(new java.awt.Color(192, 192, 192));
        complete_order_submit_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        complete_order_submit_jButton.setToolTipText("Submit");
        complete_order_submit_jButton.setBorder(null);
        complete_order_submit_jButton.setBorderPainted(false);
        complete_order_submit_jButton.setContentAreaFilled(false);
        complete_order_submit_jButton.setFocusPainted(false);
        complete_order_submit_jButton.setVerifyInputWhenFocusTarget(false);
        complete_order_UI_jPanel.add(complete_order_submit_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(complete_order_UI_jPanel, "card2");

        calendar_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        calendar_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calendar_TT_jLabel.setText("Today/Tomorrow:");
        calendar_UI_jPanel.add(calendar_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        calendar_TT_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calendar_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        calendar_UI_jPanel.add(calendar_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 170, -1));

        calendar_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00 AM", null, null, null},
                {"8:30 AM", null, null, null},
                {"9:00 AM", null, null, null},
                {"9:30 AM", null, null, null},
                {"10:00 AM", null, null, null},
                {"10:30 AM", null, null, null},
                {"11:00 AM", null, null, null},
                {"11:30 AM", null, null, null},
                {"12:00 PM", null, null, null},
                {"12:30 PM", null, null, null},
                {"1:00 PM", null, null, null},
                {"1:30 PM", null, null, null},
                {"2:00 PM", null, null, null},
                {"2:30 PM", null, null, null},
                {"3:00 PM", null, null, null},
                {"3:30 PM", null, null, null},
                {"4:00 PM", null, null, null},
                {"4:30 PM", null, null, null},
                {"5:00 PM", null, null, null},
                {"5:30 PM", null, null, null},
                {"6:00 PM", null, null, null},
                {"6:30 PM", null, null, null},
                {"7:00 PM", null, null, null},
                {"7:30 PM", null, null, null},
                {"8:00 PM", null, null, null},
                {"8:30 PM", null, null, null}
            },
            new String [] {
                "Time Slot", "Customer Name", "Customer Name", "Customer Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calendar_jTable.setFocusable(false);
        calendar_jTable.setRowSelectionAllowed(false);
        calendar_jTable.getTableHeader().setResizingAllowed(false);
        calendar_jTable.getTableHeader().setReorderingAllowed(false);
        calendar_jScrollPane.setViewportView(calendar_jTable);

        calendar_UI_jPanel.add(calendar_jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 850, 210));

        UI_jPanel.add(calendar_UI_jPanel, "card2");

        share_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        share_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_body_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        share_body_title_jLabel.setText("This must be done if OrderTracker is kept open.");
        share_UI_jPanel.add(share_body_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        share_body_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        share_body_description_jLabel.setText("<html>\nOrderTracker saves time slot data when the window is closed. If OrderTracker is not closed,<br>\nthen time slot data will not be saved nor be shared. Share will save all time slot data and share it with<br>\nother local OrderTrackers on the fly!\n</html>");
        share_UI_jPanel.add(share_body_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        share_submit_jButton.setBackground(new java.awt.Color(192, 192, 192));
        share_submit_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        share_submit_jButton.setToolTipText("Submit");
        share_submit_jButton.setBorder(null);
        share_submit_jButton.setBorderPainted(false);
        share_submit_jButton.setContentAreaFilled(false);
        share_submit_jButton.setFocusPainted(false);
        share_submit_jButton.setVerifyInputWhenFocusTarget(false);
        share_UI_jPanel.add(share_submit_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(share_UI_jPanel, "card2");

        instructions_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_howto_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_howto_jLabel.setText("How to:");
        instructions_UI_jPanel.add(instructions_howto_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        instructions_questions_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_questions_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "How do I add a customer's name to a specific time slot?", "How do I remove completed orders from a time slot?", "How do I view all time slot data?", "How do I share all time slot data with other local OrderTrackers?", "It's the morning shift, how do I shift all time slot data from tomorrow's orders to today's orders?", "What do I do if I don't know the customer's name and I want to complete their order?", "Why doesn't OrderTracker let me add more than three orders in each hour increment?" }));
        instructions_questions_jComboBox.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    Object item = event.getItem();

                    if (item.toString().equals("How do I add a customer's name to a specific time slot?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_add_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I remove completed orders from a time slot?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_complete_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I view all time slot data?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_view_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I share all time slot data with other local OrderTrackers?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_share_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("It's the morning shift, how do I shift all time slot data from tomorrow's orders to today's orders?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_shift_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("What do I do if I don't know the customer's name and I want to complete their order?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_dkcn_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("Why doesn't OrderTracker let me add more than three orders in each hour increment?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_max_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                }
            }
        });
        instructions_UI_jPanel.add(instructions_questions_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 530, -1));

        instructions_body_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_body_jPanel.setLayout(new java.awt.CardLayout());

        instructions_add_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_add_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel.setText("How do I add a customer's name to a specific time slot?");
        instructions_add_jPanel.add(instructions_body_question_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel.setText("<html>\nClick the Add Customer icon on the toolbar. This will bring you to the Add Customer page. Fill in<br>\nthe customer's name and choose whether you would like to add their name into a time slot for today<br>\nor tomorrow. Once decided, choose the time slot you and the customer agreed on for pick-up.<br>\nAfter all information is filled out, click the green checkmark button to submit your addition.\n</html>");
        instructions_add_jPanel.add(instructions_body_answer_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_add_user_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_user.PNG"))); // NOI18N
        instructions_add_jPanel.add(instructions_add_user_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_add_user_tip_jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        instructions_add_user_tip_jLabel.setText("Tip:");
        instructions_add_jPanel.add(instructions_add_user_tip_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 141, -1, -1));

        instructions_add_user_tipbody_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_add_user_tipbody_jLabel.setText("<html>You can quickly search a non-existing customer name in the search bar to bring you to the Add Customer<br>section with the customer name already filled in.</html>");
        instructions_add_jPanel.add(instructions_add_user_tipbody_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 141, -1, -1));

        instructions_body_jPanel.add(instructions_add_jPanel, "card2");

        instructions_complete_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_complete_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel2.setText("How do I remove completed orders from a time slot?");
        instructions_complete_jPanel.add(instructions_body_question_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel2.setText("<html>\nWhen an order is completed, click the Complete Order button in the toolbar. This will bring you to the<br>\nComplete Order page. If you know the customer's name, fill in the name in the designated area. If you<br>\ndo not know the customer's name, you can search for the customer's name with a given time slot. This<br>\nwill display all names associated with that specific time slot. Once the customer's name is filled in, press<br>\nthe green button with the checkmark to submit your completion.\n</html>");
        instructions_complete_jPanel.add(instructions_body_answer_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_complete_order_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/complete_order.PNG"))); // NOI18N
        instructions_complete_jPanel.add(instructions_complete_order_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_complete_order_tip_jLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        instructions_complete_order_tip_jLabel.setText("Tip:");
        instructions_complete_jPanel.add(instructions_complete_order_tip_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, -1, -1));

        instructions_complete_order_tipbody_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_complete_order_tipbody_jLabel.setText("<html>You can quickly search an existing customer name in the search bar to bring you to the Complete Order<br>section with the customer name already filled in.</html>");
        instructions_complete_jPanel.add(instructions_complete_order_tipbody_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 158, -1, -1));

        instructions_body_jPanel.add(instructions_complete_jPanel, "card2");

        instructions_view_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_view_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel3.setText("How do I view all time slot data?");
        instructions_view_jPanel.add(instructions_body_question_jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel3.setText("<html>\nTo view time slot data, click the View Time Slots button. This will take you to a page with a table with<br>\ntime slot data. To view today's time slots, select Today from the choice box, vice versa to view tomorrow's<br>\ntime slot data.\n</html>");
        instructions_view_jPanel.add(instructions_body_answer_jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_view_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view_time_slots.PNG"))); // NOI18N
        instructions_view_jPanel.add(instructions_view_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_view_jPanel, "card2");

        instructions_share_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_share_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel4.setText("How do I share all time slot data with other local OrderTrackers?");
        instructions_share_jPanel.add(instructions_body_question_jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel4.setText("<html>\nThere are two ways to share time slot data to other local OrderTrackers. The first method is by closing the<br>\nOrderTracker window, which automatically sends time slot data to local computers. You can also click the<br>\nShare button in the toolbar and then the green checkmark in the window to manually share time slot data.<br>\nIt is important to note that OrderTracker will not automatically send time slot data to local computers until it<br>\nis closed, which is why the manual share option exists.\n</html>");
        instructions_share_jPanel.add(instructions_body_answer_jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_share_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/share.PNG"))); // NOI18N
        instructions_share_jPanel.add(instructions_share_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_share_jPanel, "card2");

        instructions_shift_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_shift_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel7.setText("<html>It's the morning shift, how do I shift all time slot data from tomorrow's<br>orders to today's orders?</html>");
        instructions_shift_jPanel.add(instructions_body_question_jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel7.setText("<html>\nOrderTracker does not shift time slot data automatically. It does however shift it for you if request it<br>\nto do so. Click the Shift button in the toolbar. This will bring you to the Shift Orders section. Press the<br>\ngreen checkmark to shift orders. You will need to confirm your choice. Asking to confirm your choice is <br>\nthe way OrderTracker knows this is really what you want to do and it is not an accidental click. This is <br>\nbecause when this operation is complete, you cannot retrieve the old today's orders. They are permanently<br>\ndeleted from OrderTracker.\n</html>");
        instructions_shift_jPanel.add(instructions_body_answer_jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        instructions_shift_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shift.PNG"))); // NOI18N
        instructions_shift_jPanel.add(instructions_shift_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_shift_jPanel, "card2");

        instructions_dkcn_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_dkcn_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel5.setText("What do I do if I don't know the customer's name and I want to complete their order?");
        instructions_dkcn_jPanel.add(instructions_body_question_jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel5.setText("<html>\n If you do not know the customer's name, you can search for the customer's name with a given time slot. To do<br>\nthis, first click the Complete Order button in the toolbar. Once there, you will be presented with the option to search<br>\nby time slot. Choose the time slot you are looking for which will display all customer names associated with that specific<br>\ntime slot to help you when searching. Once the customer's name is filled in, press the green button with the checkmark<br>\nto submit your completion.\n</html>");
        instructions_dkcn_jPanel.add(instructions_body_answer_jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_body_jPanel.add(instructions_dkcn_jPanel, "card2");

        instructions_max_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_max_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel6.setText("Why doesn't OrderTracker let me add more than three orders in each hour increment?");
        instructions_max_jPanel.add(instructions_body_question_jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel6.setText("<html>\nOrderTracker will only allow a maximum of three orders for each hour increment. This is due to the fact that<br>\noverbooking is an easy and quick way to overburden you and your coworkers in the Copy & Print Center.<br>\nOrderTracker will attempt to minimize the amount of overbooking done by giving a maximum to the amount of<br>\norders that are allowed to be taken in a given hour.\n</html>");
        instructions_max_jPanel.add(instructions_body_answer_jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_body_jPanel.add(instructions_max_jPanel, "card2");

        instructions_UI_jPanel.add(instructions_body_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 850, 190));

        UI_jPanel.add(instructions_UI_jPanel, "card2");

        credits_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        credits_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        credits_jTextArea.setEditable(false);
        credits_jTextArea.setBackground(new java.awt.Color(185, 185, 185));
        credits_jTextArea.setColumns(20);
        credits_jTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_jTextArea.setRows(5);
        credits_jTextArea.setText("Developed by Jori El-Saikali.\n\nA special thanks to all the staff at Store 16! Without them I would have never created OrderTracker. Thank you all!\n\nThank you to my good friend Jed Lloren for testing OrderTracker as well as fixing any grammar and spelling mistakes I made.\n\nResource Credits:\n\nHouse black silhouette without door icon made by Freepik from www.flaticon.com\nNew user free icon made by Freepik from www.flaticon.com\nChecked free icon made by Smashicons from www.flaticon.com\nCalendar free icon made by Smashicons from www.flaticon.com\nLocal network free icon made by Nikita Golubev from www.flaticon.com\nSearch free icon made by Smashicons from www.flaticon.com\nThumbs up free icon made by Dave Gandy from www.flaticon.com\nInstructions free icon made by Smashicons from www.flaticon.com\nVerified notes symbol free icon made by Freepik from www.flaticon.com\nShift keyboard key free icon made by Freepik from www.flaticon.com\nSupport free icon made by Good Ware from www.flaticon.com\nSettings Work Tool free icon made by Egor Rumyantsev from www.flaticon.com");
        credits_jScrollPane.setViewportView(credits_jTextArea);

        credits_UI_jPanel.add(credits_jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 63, 860, 190));

        UI_jPanel.add(credits_UI_jPanel, "card2");

        add_user_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        add_user_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TS_jLabel.setText("Time Slot:");
        add_user_UI_jPanel.add(add_user_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        add_user_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jLabel.setText("Customer's Name:");
        add_user_UI_jPanel.add(add_user_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        add_user_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TT_jLabel.setText("Today/Tomorrow:");
        add_user_UI_jPanel.add(add_user_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 128, -1, -1));

        add_user_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jTextField.setBorder(null);
        add_user_CN_jTextField.setOpaque(false);
        add_user_CN_jTextField.setBackground(new Color(0,0,0,0));

        add_user_UI_jPanel.add(add_user_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 66, 340, 30));
        add_user_UI_jPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 96, 340, -1));

        add_user_TT_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_user_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        add_user_UI_jPanel.add(add_user_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        add_user_TS_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_user_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        add_user_UI_jPanel.add(add_user_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, -1));

        add_user_submit_jButton.setBackground(new java.awt.Color(192, 192, 192));
        add_user_submit_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        add_user_submit_jButton.setToolTipText("Submit");
        add_user_submit_jButton.setBorder(null);
        add_user_submit_jButton.setBorderPainted(false);
        add_user_submit_jButton.setContentAreaFilled(false);
        add_user_submit_jButton.setFocusPainted(false);
        add_user_submit_jButton.setVerifyInputWhenFocusTarget(false);
        add_user_UI_jPanel.add(add_user_submit_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(add_user_UI_jPanel, "card2");

        shift_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        shift_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shift_body_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shift_body_title_jLabel.setText("This must be done every morning when OrderTracker is first opened.");
        shift_UI_jPanel.add(shift_body_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        shift_body_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shift_body_description_jLabel.setText("<html>\nOrderTracker does not automatically shift orders from tomorrow's orders to today's orders. This means<br>\nthat orders must manually be shifted. But don't worry! OrderTracker still makes this easy for you! By just <br>\npressing the submit button and confirming, OrderTracker will shift all orders for you!\n</html>");
        shift_UI_jPanel.add(shift_body_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        shift_submit_jButton.setBackground(new java.awt.Color(192, 192, 192));
        shift_submit_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        shift_submit_jButton.setToolTipText("Submit");
        shift_submit_jButton.setBorder(null);
        shift_submit_jButton.setBorderPainted(false);
        shift_submit_jButton.setContentAreaFilled(false);
        shift_submit_jButton.setFocusPainted(false);
        shift_submit_jButton.setVerifyInputWhenFocusTarget(false);
        shift_UI_jPanel.add(shift_submit_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(shift_UI_jPanel, "card2");

        settings_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        settings_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        settings_submit_jButton.setBackground(new java.awt.Color(192, 192, 192));
        settings_submit_jButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        settings_submit_jButton.setToolTipText("Submit");
        settings_submit_jButton.setBorder(null);
        settings_submit_jButton.setBorderPainted(false);
        settings_submit_jButton.setContentAreaFilled(false);
        settings_submit_jButton.setFocusPainted(false);
        settings_submit_jButton.setVerifyInputWhenFocusTarget(false);
        settings_UI_jPanel.add(settings_submit_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        settings_path_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settings_path_jLabel.setText("Path to save persistent data to:");
        settings_UI_jPanel.add(settings_path_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 120, -1, -1));

        settings_max_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        settings_UI_jPanel.add(settings_max_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 60, -1));

        settings_max_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        settings_max_jLabel.setText("Maximum amount of orders allowed per hour:");
        settings_UI_jPanel.add(settings_max_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        settings_path_jTextField.setEditable(false);
        settings_path_jTextField.setFocusable(false);
        settings_UI_jPanel.add(settings_path_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 360, 20));

        settings_file_chooser_jButton.setText("...");
        settings_file_chooser_jButton.setBorder(null);
        settings_file_chooser_jButton.setBorderPainted(false);
        settings_file_chooser_jButton.setFocusPainted(false);
        settings_UI_jPanel.add(settings_file_chooser_jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 20, 20));

        UI_jPanel.add(settings_UI_jPanel, "card2");

        getContentPane().add(UI_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 970, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_jTextFieldKeyPressed
       transitionToSearch(evt);
    }//GEN-LAST:event_search_jTextFieldKeyPressed

    private void home_instructions_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_instructions_jButtonActionPerformed
        transitionToInstructions();
    }//GEN-LAST:event_home_instructions_jButtonActionPerformed

    private void home_credits_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_credits_jButtonActionPerformed
        transitionToCredits();
    }//GEN-LAST:event_home_credits_jButtonActionPerformed

    private void toolbar_home_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_home_jButtonActionPerformed
        transitionToHome();
    }//GEN-LAST:event_toolbar_home_jButtonActionPerformed

    private void toolbar_add_user_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_add_user_jButtonActionPerformed
        transitionToAddUser();
    }//GEN-LAST:event_toolbar_add_user_jButtonActionPerformed

    private void toolbar_complete_order_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_complete_order_jButtonActionPerformed
        transitionToCompleteOrder();
    }//GEN-LAST:event_toolbar_complete_order_jButtonActionPerformed

    private void toolbar_calendar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_calendar_jButtonActionPerformed
        transitionToCalendar();
    }//GEN-LAST:event_toolbar_calendar_jButtonActionPerformed

    private void toolbar_share_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_share_jButtonActionPerformed
        transitionToShare();
    }//GEN-LAST:event_toolbar_share_jButtonActionPerformed

    private void search_jTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_jTextFieldMouseClicked
        if (search_jTextField.getText().equals("Search a non-existing or existing customer name for quick addition or completion")) {
            clearSearch();
        }
    }//GEN-LAST:event_search_jTextFieldMouseClicked

    private void toolbar_shift_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_shift_jButtonActionPerformed
        transitionToShift();
    }//GEN-LAST:event_toolbar_shift_jButtonActionPerformed

    private void complete_order_TS_jComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_complete_order_TS_jComboBoxItemStateChanged
        complete_order_TS_jComboBox.addItemListener((ItemEvent event) -> {
            if (event.getStateChange() == ItemEvent.SELECTED) {
                Object item = event.getItem();
                
                if (item.toString().equals("None")) {
                    complete_order_jScrollPane.setVisible(false);
                    complete_order_CN_jTable.setVisible(false);
                }
                else {
                    complete_order_jScrollPane.setVisible(true);
                    complete_order_CN_jTable.setVisible(true);
                    
                    updateRow();
                }
            }
        });
    }//GEN-LAST:event_complete_order_TS_jComboBoxItemStateChanged

    private void complete_order_TT_jComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_complete_order_TT_jComboBoxItemStateChanged
        complete_order_TT_jComboBox.addItemListener((ItemEvent event) -> {
            if (isRowVisible()) {
                Object item = event.getItem();

                String time = complete_order_TS_jComboBox.getSelectedItem().toString();
                String todayOrTomorrow = complete_order_TT_jComboBox.getSelectedItem().toString();

                TimeSlot[] row = model.getRow(time, todayOrTomorrow);

                complete_order_CN_jTable.setValueAt(row[0].GetCustomerName(), 0, 0);
                complete_order_CN_jTable.setValueAt(row[1].GetCustomerName(), 0, 1);
                complete_order_CN_jTable.setValueAt(row[2].GetCustomerName(), 0, 2);

                for (int i = 0; i < complete_order_CN_jTable.getColumnCount(); i++) {
                    if (complete_order_CN_jTable.getValueAt(0, i).equals("null")) {
                        complete_order_CN_jTable.setValueAt("", 0, i);
                    }  
                }
            }
        });
    }//GEN-LAST:event_complete_order_TT_jComboBoxItemStateChanged

    private void toolbar_support_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_support_jButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolbar_support_jButtonActionPerformed

    private void toolbar_settings_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolbar_settings_jButtonActionPerformed
        transitionToSettings();
    }//GEN-LAST:event_toolbar_settings_jButtonActionPerformed

    
    public void runGFX() {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderTrackerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderTrackerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderTrackerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderTrackerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        this.setVisible(true);
    }
    
    // ---------------- Adding Customer functions ----------------- //
    public String getAddUserCN() { return add_user_CN_jTextField.getText(); }
    public String getAddUserTT() { return add_user_TT_jComboBox.getSelectedItem().toString(); }
    public String getAddUserTS() { return add_user_TS_jComboBox.getSelectedItem().toString(); }
    
    public void clearAddUserCN() { add_user_CN_jTextField.setText(""); }
    // ------------------------------------------------------------ //
    
    // ---------------- Completing Order functions ---------------- //
    public String getCompleteOrderCN() { return complete_order_CN_jTextField.getText(); }
    public String getCompleteOrderTS() { return complete_order_TS_jComboBox.getSelectedItem().toString(); }
    
    public void clearCompleteOrderCN() { complete_order_CN_jTextField.setText(""); }
    
    public boolean isRowVisible() { return complete_order_CN_jTable.isVisible(); }
    public void updateRow() {
        String time = complete_order_TS_jComboBox.getSelectedItem().toString();
        String todayOrTomorrow = complete_order_TT_jComboBox.getSelectedItem().toString();
                    
        TimeSlot[] row = model.getRow(time, todayOrTomorrow);
                    
        complete_order_CN_jTable.setValueAt(row[0].GetCustomerName(), 0, 0);
        complete_order_CN_jTable.setValueAt(row[1].GetCustomerName(), 0, 1);
        complete_order_CN_jTable.setValueAt(row[2].GetCustomerName(), 0, 2);
                    
        for (int i = 0; i < complete_order_CN_jTable.getColumnCount(); i++) {
            if (complete_order_CN_jTable.getValueAt(0, i) == null || complete_order_CN_jTable.getValueAt(0, i).equals("null")) {
                complete_order_CN_jTable.setValueAt("", 0, i);
            }
        }
    }
    // ------------------------------------------------------------ //
    
    // ---------------- Calendar functions ---------------- //
    public String getCalendarTT() { return calendar_TT_jComboBox.getSelectedItem().toString(); }
    
    public void rebuildTable(int range) {
        for (int i = 0; i < calendar_jTable.getColumnCount()-1; i++) {
            calendar_jTable.removeColumn(calendar_jTable.getColumn("Customer Name"));
        }
        
        for (int i = 0; i <= range; i++) {
            TableColumn col = new TableColumn();
            col.setHeaderValue("Customer Name");
            calendar_jTable.addColumn(col);
        }
    }
    
    public void updateCalendarTable(TimeSlot[] timeslots) {
        
        int count = 1, i = 0;
        for (TimeSlot slot : timeslots) {
            if (count == 4) {
                i++;
                count = 1;
            }
            
            calendar_jTable.setValueAt(slot.GetCustomerName(), i, count);
            count++;
        }
        
        TableModel tableModel = calendar_jTable.getModel();
        
        for (int row = 0; row < calendar_jTable.getRowCount(); row++) {
            for (int column = 1; column < 4; column++) {
                String selected = "";
                if (tableModel.getValueAt(row, column) != null) {
                    selected = tableModel.getValueAt(row, column).toString();
                }
            
                if (selected.equals("null")) {
                    calendar_jTable.setValueAt("", row, column);
                }
            }
        }
    }
    // ---------------------------------------------------- //
    
    // --------------------- Shift function ---------------------- //
    public int confirmDialogBox(String message) {
        JFrame frame = new JFrame();
        int answer = JOptionPane.showConfirmDialog(frame, message, "Select an Option", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            return 0;
        }
        else if (answer == JOptionPane.NO_OPTION) {
            return 1;
        }
        
        return -1;
    }
    // ----------------------------------------------------------- //
    
    // ------------------- Settings functions -------------------- //
    public String getSettingsMax() { return settings_max_jComboBox.getSelectedItem().toString(); }
    //public String getSettingsPath() { return settings_path_jTextField.getText(); }
    
    public void setSettingsMax(String max) { settings_max_jComboBox.setSelectedItem(max); }
    //public void setSettingsPath(String path) { settings_path_jTextField.setText(path); }
    // ----------------------------------------------------------- //
    
    // --------------------- Search function -------------------- //
    public void clearSearch() { search_jTextField.setText(""); }
    public void setToSearchDefault() { search_jTextField.setText("Search a non-existing or existing customer name for quick addition or completion"); }
    // ---------------------------------------------------------- //
    
    // ------------------ Adding Listeners ------------------- //
    public void addAddCustomerButtonListener(ActionListener listener) {
        add_user_submit_jButton.addActionListener(listener);
    }
    
    public void addCompleteOrderButtonListener(ActionListener listener) {
        complete_order_submit_jButton.addActionListener(listener);
    }
    
    public void addCalendarToolbarButtonListener(ActionListener listener) {
        toolbar_calendar_jButton.addActionListener(listener);
    }
    
    public void addCalendarTTActionListener(ActionListener listener) {
        calendar_TT_jComboBox.addActionListener(listener);
    }
    
    public void addShareButtonListener(ActionListener listener) {
        share_submit_jButton.addActionListener(listener);
    }
    
    public void addShiftButtonListener(ActionListener listener) {
        shift_submit_jButton.addActionListener(listener);
    }
    
    public void addSettingsToolbarButtonListener(ActionListener listener) {
        toolbar_settings_jButton.addActionListener(listener);
    }
    
    public void addSettingsButtonListener(ActionListener listener) {
        settings_submit_jButton.addActionListener(listener);
    }
    // ------------------------------------------------------- //
    
    // ---------------- Transition functions ---------------- //
    public void transitionToHome() {
        UI_jPanel.removeAll();
        UI_jPanel.add(home_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(home_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        setToSearchDefault();
    }
    
    public void transitionToAddUser() {
        UI_jPanel.removeAll();
        UI_jPanel.add(add_user_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(add_user_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        add_user_CN_jTextField.setText("");
        add_user_TT_jComboBox.setSelectedIndex(0);
        add_user_TS_jComboBox.setSelectedIndex(0);
        setToSearchDefault();
    }
    
    public void transitionToCompleteOrder() {
        UI_jPanel.removeAll();
        UI_jPanel.add(complete_order_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(complete_order_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        complete_order_CN_jTextField.setText("");
        complete_order_TS_jComboBox.setSelectedIndex(0);
        setToSearchDefault();
    }
    
    public void transitionToCalendar() {
        UI_jPanel.removeAll();
        UI_jPanel.add(calendar_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(calendar_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        calendar_TT_jComboBox.setSelectedIndex(0);
        
        setToSearchDefault();
    }
    
    public void transitionToShare() {
        UI_jPanel.removeAll();
        UI_jPanel.add(share_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(share_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        setToSearchDefault();
    }
    
    public void transitionToShift() {
        UI_jPanel.removeAll();
        UI_jPanel.add(shift_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(shift_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        setToSearchDefault();
    }
    
    public void transitionToSettings() { 
        UI_jPanel.removeAll();
        UI_jPanel.add(settings_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(settings_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        setToSearchDefault();
    }
    
    public void transitionToInstructions() {
        UI_jPanel.removeAll();
        UI_jPanel.add(instructions_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(instructions_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        setToSearchDefault();
    }
    
    public void transitionToCredits() {
        UI_jPanel.removeAll();
        UI_jPanel.add(credits_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(credits_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
        
        setToSearchDefault();
    }
    
    public void transitionToSearch(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
           // Search
           
           String searched = search_jTextField.getText();
           
           if (searched.contains("<html>")) {
               clearSearch();
               displayError("Search contains html code. This is not allowed.");
               return;
           }
           
           if (model.hasCustomer(searched)) {
               transitionToCompleteOrder();
               complete_order_CN_jTextField.setText(searched);
               search_jTextField.setText(searched);
           }
           else {
               transitionToAddUser();
               add_user_CN_jTextField.setText(searched);
               search_jTextField.setText(searched);
           }
       }
    }
    // ------------------------------------------------------ //
    
    // -------------------- Success/Error Message function ------------------ //
    public void displaySuccess() {
        JOptionPane.showMessageDialog(this, "Operation successful.");
    }
    
    public void displayError(String error) {
        JOptionPane.showMessageDialog(this, "Error has occured.\n" + error);
    }
    
    public void displayMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    // -------------------------------------------------------------- //
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UI_jPanel;
    private javax.swing.JLabel add_user_CN_jLabel;
    private javax.swing.JTextField add_user_CN_jTextField;
    private javax.swing.JComboBox<String> add_user_TS_jComboBox;
    private javax.swing.JLabel add_user_TS_jLabel;
    private javax.swing.JComboBox<String> add_user_TT_jComboBox;
    private javax.swing.JLabel add_user_TT_jLabel;
    private javax.swing.JPanel add_user_UI_jPanel;
    private javax.swing.JButton add_user_submit_jButton;
    private javax.swing.JLabel add_user_subtitle_jLabel;
    private javax.swing.JLabel add_user_title_jLabel;
    private javax.swing.JPanel add_user_title_jPanel;
    private javax.swing.JComboBox<String> calendar_TT_jComboBox;
    private javax.swing.JLabel calendar_TT_jLabel;
    private javax.swing.JPanel calendar_UI_jPanel;
    private javax.swing.JScrollPane calendar_jScrollPane;
    private javax.swing.JTable calendar_jTable;
    private javax.swing.JLabel calendar_subtitle_jLabel;
    private javax.swing.JLabel calendar_title_jLabel;
    private javax.swing.JPanel calendar_title_jPanel;
    private javax.swing.JLabel complete_order_CN_jLabel;
    private javax.swing.JTable complete_order_CN_jTable;
    private javax.swing.JTextField complete_order_CN_jTextField;
    private javax.swing.JComboBox<String> complete_order_TS_jComboBox;
    private javax.swing.JLabel complete_order_TS_jLabel;
    private javax.swing.JComboBox<String> complete_order_TT_jComboBox;
    private javax.swing.JLabel complete_order_TT_jLabel;
    private javax.swing.JPanel complete_order_UI_jPanel;
    private javax.swing.JScrollPane complete_order_jScrollPane;
    private javax.swing.JButton complete_order_submit_jButton;
    private javax.swing.JLabel complete_order_subtitle_jLabel1;
    private javax.swing.JLabel complete_order_title_jLabel1;
    private javax.swing.JPanel complete_order_title_jPanel;
    private javax.swing.JPanel credits_UI_jPanel;
    private javax.swing.JLabel credits_description_jLabel;
    private javax.swing.JScrollPane credits_jScrollPane;
    private javax.swing.JTextArea credits_jTextArea;
    private javax.swing.JLabel credits_main_title_jLabel;
    private javax.swing.JLabel credits_subtitle_jLabel;
    private javax.swing.JLabel credits_title_jLabel;
    private javax.swing.JPanel credits_title_jPanel;
    private javax.swing.JPanel home_UI_jPanel;
    private javax.swing.JButton home_credits_jButton;
    private javax.swing.JButton home_instructions_jButton;
    private javax.swing.JPanel home_title_jPanel;
    private javax.swing.JPanel instructions_UI_jPanel;
    private javax.swing.JPanel instructions_add_jPanel;
    private javax.swing.JLabel instructions_add_user_icon_jLabel;
    private javax.swing.JLabel instructions_add_user_tip_jLabel;
    private javax.swing.JLabel instructions_add_user_tipbody_jLabel;
    private javax.swing.JLabel instructions_body_answer_jLabel;
    private javax.swing.JLabel instructions_body_answer_jLabel2;
    private javax.swing.JLabel instructions_body_answer_jLabel3;
    private javax.swing.JLabel instructions_body_answer_jLabel4;
    private javax.swing.JLabel instructions_body_answer_jLabel5;
    private javax.swing.JLabel instructions_body_answer_jLabel6;
    private javax.swing.JLabel instructions_body_answer_jLabel7;
    private javax.swing.JPanel instructions_body_jPanel;
    private javax.swing.JLabel instructions_body_question_jLabel;
    private javax.swing.JLabel instructions_body_question_jLabel2;
    private javax.swing.JLabel instructions_body_question_jLabel3;
    private javax.swing.JLabel instructions_body_question_jLabel4;
    private javax.swing.JLabel instructions_body_question_jLabel5;
    private javax.swing.JLabel instructions_body_question_jLabel6;
    private javax.swing.JLabel instructions_body_question_jLabel7;
    private javax.swing.JPanel instructions_complete_jPanel;
    private javax.swing.JLabel instructions_complete_order_icon_jLabel;
    private javax.swing.JLabel instructions_complete_order_tip_jLabel;
    private javax.swing.JLabel instructions_complete_order_tipbody_jLabel;
    private javax.swing.JLabel instructions_description_jLabel;
    private javax.swing.JPanel instructions_dkcn_jPanel;
    private javax.swing.JLabel instructions_howto_jLabel;
    private javax.swing.JLabel instructions_main_title_jLabel;
    private javax.swing.JPanel instructions_max_jPanel;
    private javax.swing.JComboBox<String> instructions_questions_jComboBox;
    private javax.swing.JLabel instructions_share_icon_jLabel;
    private javax.swing.JPanel instructions_share_jPanel;
    private javax.swing.JLabel instructions_shift_icon_jLabel;
    private javax.swing.JPanel instructions_shift_jPanel;
    private javax.swing.JLabel instructions_subtitle_jLabel;
    private javax.swing.JLabel instructions_title_jLabel;
    private javax.swing.JPanel instructions_title_jPanel;
    private javax.swing.JLabel instructions_view_icon_jLabel;
    private javax.swing.JPanel instructions_view_jPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel order_tracker_jLabel;
    private javax.swing.JPanel search_area_jPanel;
    private javax.swing.JLabel search_icon_jLabel;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JLabel search_main_title_jLabel;
    private javax.swing.JLabel search_main_title_jLabel1;
    private javax.swing.JLabel search_subtitle_jLabel;
    private javax.swing.JLabel search_subtitle_jLabel1;
    private javax.swing.JPanel search_title_jPanel;
    private javax.swing.JPanel settings_UI_jPanel;
    private javax.swing.JButton settings_file_chooser_jButton;
    private javax.swing.JComboBox<String> settings_max_jComboBox;
    private javax.swing.JLabel settings_max_jLabel;
    private javax.swing.JLabel settings_path_jLabel;
    private javax.swing.JTextField settings_path_jTextField;
    private javax.swing.JButton settings_submit_jButton;
    private javax.swing.JPanel settings_title_jPanel;
    private javax.swing.JPanel share_UI_jPanel;
    private javax.swing.JLabel share_body_description_jLabel;
    private javax.swing.JLabel share_body_title_jLabel;
    private javax.swing.JButton share_submit_jButton;
    private javax.swing.JLabel share_subtitle_jLabel;
    private javax.swing.JLabel share_title_jLabel;
    private javax.swing.JPanel share_title_jPanel;
    private javax.swing.JPanel shift_UI_jPanel;
    private javax.swing.JLabel shift_body_description_jLabel;
    private javax.swing.JLabel shift_body_title_jLabel;
    private javax.swing.JLabel shift_main_title_jLabel;
    private javax.swing.JButton shift_submit_jButton;
    private javax.swing.JLabel shift_subtitle_jLabel;
    private javax.swing.JPanel shift_title_jPanel;
    private javax.swing.JLabel staples_logo_jLabel;
    private javax.swing.JPanel title_jPanel;
    private javax.swing.JButton toolbar_add_user_jButton;
    private javax.swing.JPanel toolbar_blank_jPanel;
    private javax.swing.JButton toolbar_calendar_jButton;
    private javax.swing.JButton toolbar_complete_order_jButton;
    private javax.swing.JButton toolbar_home_jButton;
    private javax.swing.JPanel toolbar_jPanel;
    private javax.swing.JButton toolbar_settings_jButton;
    private javax.swing.JButton toolbar_share_jButton;
    private javax.swing.JButton toolbar_shift_jButton;
    private javax.swing.JButton toolbar_support_jButton;
    private javax.swing.JPanel toolbar_support_jPanel;
    private javax.swing.JLabel welcome_jLabel;
    // End of variables declaration//GEN-END:variables
}
