/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordertracker_old;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;

/**
 *
 * @author Jori El-Saikali
 */
public class Home extends javax.swing.JFrame {

    public String action = "";
    public boolean running = false;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocation(300,100);
        this.setSize(1029, 657);
        initialize();
        running = true;
    }

    private void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("resources/verified-notes-symbol.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        toolbar_jPanel = new javax.swing.JPanel();
        home_jLabel = new javax.swing.JLabel();
        add_user_jLabel = new javax.swing.JLabel();
        complete_order_jLabel = new javax.swing.JLabel();
        calendar_jLabel = new javax.swing.JLabel();
        share_jLabel = new javax.swing.JLabel();
        toolbar_blank_jPanel = new javax.swing.JPanel();
        search_area_jPanel = new javax.swing.JPanel();
        search_icon_jLabel = new javax.swing.JLabel();
        search_jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        staples_logo_jLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        title_jPanel = new javax.swing.JPanel();
        home_title_jPanel = new javax.swing.JPanel();
        welcome_jLabel = new javax.swing.JLabel();
        order_tracker_jLabel = new javax.swing.JLabel();
        add_user_title_jPanel = new javax.swing.JPanel();
        add_user_subtitle_jLabel = new javax.swing.JLabel();
        add_user_title_jLabel = new javax.swing.JLabel();
        complete_order_title_jPanel = new javax.swing.JPanel();
        complete_order_subtitle_jLabel1 = new javax.swing.JLabel();
        complete_order_title_jLabel1 = new javax.swing.JLabel();
        calendar_title_jPanel = new javax.swing.JPanel();
        calendar_subtitle_jLabel = new javax.swing.JLabel();
        calendar_title_jLabel = new javax.swing.JLabel();
        share_title_jPanel = new javax.swing.JPanel();
        share_subtitle_jLabel = new javax.swing.JLabel();
        share_title_jLabel = new javax.swing.JLabel();
        instructions_title_jPanel = new javax.swing.JPanel();
        instructions_subtitle_jLabel = new javax.swing.JLabel();
        instructions_main_title_jLabel = new javax.swing.JLabel();
        credits_title_jPanel = new javax.swing.JPanel();
        credits_subtitle_jLabel = new javax.swing.JLabel();
        credits_main_title_jLabel = new javax.swing.JLabel();
        search_title_jPanel = new javax.swing.JPanel();
        search_subtitle_jLabel = new javax.swing.JLabel();
        search_main_title_jLabel = new javax.swing.JLabel();
        UI_jPanel = new javax.swing.JPanel();
        home_UI_jPanel = new javax.swing.JPanel();
        thumbs_up_jLabel = new javax.swing.JLabel();
        instructions_icon_jLabel = new javax.swing.JLabel();
        instructions_title_jLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        credits_title_jLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        credits_description_jLabel = new javax.swing.JLabel();
        instructions_description_jLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        complete_order_UI_jPanel = new javax.swing.JPanel();
        complete_order_CN_jLabel = new javax.swing.JLabel();
        complete_order_CN_jTextField = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        complete_order_TS_jLabel = new javax.swing.JLabel();
        complete_order_TS_jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        complete_order_submit_jLabel = new javax.swing.JLabel();
        calendar_UI_jPanel = new javax.swing.JPanel();
        calendar_TT_jLabel = new javax.swing.JLabel();
        calendar_TT_jComboBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        calendar_jTable = new javax.swing.JTable();
        share_UI_jPanel = new javax.swing.JPanel();
        share_body_title_jLabel = new javax.swing.JLabel();
        share_body_description_jLabel = new javax.swing.JLabel();
        share_submit_jLabel = new javax.swing.JLabel();
        instructions_UI_jPanel = new javax.swing.JPanel();
        instructions_howto_jLabel = new javax.swing.JLabel();
        instructions_questions_jComboBox = new javax.swing.JComboBox<>();
        instructions_body_jPanel = new javax.swing.JPanel();
        instructions_add_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel = new javax.swing.JLabel();
        instructions_body_answer_jLabel = new javax.swing.JLabel();
        instructions_add_user_icon_jLabel = new javax.swing.JLabel();
        instructions_complete_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel2 = new javax.swing.JLabel();
        instructions_body_answer_jLabel2 = new javax.swing.JLabel();
        instructions_complete_order_icon_jLabel = new javax.swing.JLabel();
        instructions_view_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel3 = new javax.swing.JLabel();
        instructions_body_answer_jLabel3 = new javax.swing.JLabel();
        instructions_view_icon_jLabel = new javax.swing.JLabel();
        instructions_share_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel4 = new javax.swing.JLabel();
        instructions_body_answer_jLabel4 = new javax.swing.JLabel();
        instructions_share_icon_jLabel = new javax.swing.JLabel();
        instructions_dkcn_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel5 = new javax.swing.JLabel();
        instructions_body_answer_jLabel5 = new javax.swing.JLabel();
        instructions_max_jPanel = new javax.swing.JPanel();
        instructions_body_question_jLabel6 = new javax.swing.JLabel();
        instructions_body_answer_jLabel6 = new javax.swing.JLabel();
        credits_UI_jPanel = new javax.swing.JPanel();
        credits_body_title_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        credits_jTextArea = new javax.swing.JTextArea();
        search_UI_jPanel = new javax.swing.JPanel();
        search_body_title_jLabel = new javax.swing.JLabel();
        search_results_jPanel = new javax.swing.JPanel();
        add_user_UI_jPanel = new javax.swing.JPanel();
        add_user_TS_jLabel = new javax.swing.JLabel();
        add_user_CN_jLabel = new javax.swing.JLabel();
        add_user_TT_jLabel = new javax.swing.JLabel();
        add_user_CN_jTextField = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        add_user_TT_jComboBox = new javax.swing.JComboBox<>();
        add_user_TS_jComboBox = new javax.swing.JComboBox<>();
        add_user_submit_jLabel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OrderTracker");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(1029, 657));
        setName("main_frame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toolbar_jPanel.setBackground(new java.awt.Color(104, 100, 100));
        toolbar_jPanel.setLayout(new java.awt.GridLayout(5, 1));

        home_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/house-black-silhouette-without-door.png"))); // NOI18N
        home_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(home_jLabel);

        add_user_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_user_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/new-user.png"))); // NOI18N
        add_user_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_user_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(add_user_jLabel);

        complete_order_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        complete_order_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/checked.png"))); // NOI18N
        complete_order_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complete_order_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(complete_order_jLabel);

        calendar_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendar_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calendar.png"))); // NOI18N
        calendar_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendar_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(calendar_jLabel);

        share_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        share_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/local-network.png"))); // NOI18N
        share_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                share_jLabelMouseClicked(evt);
            }
        });
        toolbar_jPanel.add(share_jLabel);

        getContentPane().add(toolbar_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 460));

        toolbar_blank_jPanel.setBackground(new java.awt.Color(104, 100, 100));

        javax.swing.GroupLayout toolbar_blank_jPanelLayout = new javax.swing.GroupLayout(toolbar_blank_jPanel);
        toolbar_blank_jPanel.setLayout(toolbar_blank_jPanelLayout);
        toolbar_blank_jPanelLayout.setHorizontalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        toolbar_blank_jPanelLayout.setVerticalGroup(
            toolbar_blank_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(toolbar_blank_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 60, 210));

        search_area_jPanel.setBackground(new java.awt.Color(244, 237, 237));
        search_area_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        search_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search.png"))); // NOI18N
        search_area_jPanel.add(search_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 0, 48, 50));

        search_jTextField.setBackground(new java.awt.Color(0, 0, 0));
        search_jTextField.setBorder(null);
        search_jTextField.setOpaque(false);
        search_jTextField.setBackground(new Color(0,0,0,0));
        search_jTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_jTextFieldKeyPressed(evt);
            }
        });
        search_area_jPanel.add(search_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, 531, 28));
        search_area_jPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 37, 531, -1));

        staples_logo_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/staples--english-french-logo-2.png"))); // NOI18N
        search_area_jPanel.add(staples_logo_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 11, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        search_area_jPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 12, -1, 24));

        getContentPane().add(search_area_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 0, 980, 50));

        title_jPanel.setBackground(new java.awt.Color(255, 255, 255));
        title_jPanel.setLayout(new java.awt.CardLayout());

        home_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        home_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        welcome_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        welcome_jLabel.setText("Welcome To");
        home_title_jPanel.add(welcome_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 258, -1));

        order_tracker_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        order_tracker_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        order_tracker_jLabel.setText("Order Tracker");
        home_title_jPanel.add(order_tracker_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, 537, -1));

        title_jPanel.add(home_title_jPanel, "card2");

        add_user_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        add_user_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        add_user_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_subtitle_jLabel.setText("Adding a customer's name to a specific time slot");
        add_user_title_jPanel.add(add_user_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        add_user_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        add_user_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        add_user_title_jLabel.setText("Add A Customer");
        add_user_title_jPanel.add(add_user_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(add_user_title_jPanel, "card2");

        complete_order_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        complete_order_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_subtitle_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        complete_order_subtitle_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_subtitle_jLabel1.setText("Remove finished orders at a specific time slot.");
        complete_order_title_jPanel.add(complete_order_subtitle_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        complete_order_title_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        complete_order_title_jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        complete_order_title_jLabel1.setText("Complete Order");
        complete_order_title_jPanel.add(complete_order_title_jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(complete_order_title_jPanel, "card2");

        calendar_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        calendar_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calendar_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_subtitle_jLabel.setText("View all time slots for either today or tomorrow.");
        calendar_title_jPanel.add(calendar_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        calendar_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        calendar_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        calendar_title_jLabel.setText("Time Slots");
        calendar_title_jPanel.add(calendar_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(calendar_title_jPanel, "card2");

        share_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        share_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        share_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_subtitle_jLabel.setText("Share time slot data with other local Order Trackers.");
        share_title_jPanel.add(share_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 850, -1));

        share_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        share_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        share_title_jLabel.setText("Share");
        share_title_jPanel.add(share_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 550, -1));

        title_jPanel.add(share_title_jPanel, "card2");

        instructions_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        instructions_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        instructions_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructions_subtitle_jLabel.setText("The how-to's on using Order Tracker");
        instructions_title_jPanel.add(instructions_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 790, -1));

        instructions_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        instructions_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        instructions_main_title_jLabel.setText("Instructions");
        instructions_title_jPanel.add(instructions_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(instructions_title_jPanel, "card2");

        credits_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        credits_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        credits_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        credits_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        credits_subtitle_jLabel.setText("Credits given to those who made Order Tracker possible");
        credits_title_jPanel.add(credits_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        credits_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        credits_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        credits_main_title_jLabel.setText("Credits");
        credits_title_jPanel.add(credits_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(credits_title_jPanel, "card2");

        search_title_jPanel.setBackground(new java.awt.Color(224, 31, 31));
        search_title_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_subtitle_jLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        search_subtitle_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        search_subtitle_jLabel.setText("An easy way to find customers and other things!");
        search_title_jPanel.add(search_subtitle_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 900, -1));

        search_main_title_jLabel.setFont(new java.awt.Font("Tahoma", 0, 78)); // NOI18N
        search_main_title_jLabel.setForeground(new java.awt.Color(255, 255, 255));
        search_main_title_jLabel.setText("Search");
        search_title_jPanel.add(search_main_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 570, -1));

        title_jPanel.add(search_title_jPanel, "card2");

        getContentPane().add(title_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 980, 260));

        UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        UI_jPanel.setLayout(new java.awt.CardLayout());

        home_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        home_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        thumbs_up_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thumbs_up_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/thumbs-up.png"))); // NOI18N
        thumbs_up_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thumbs_up_jLabelMouseClicked(evt);
            }
        });
        home_UI_jPanel.add(thumbs_up_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 88, -1, -1));

        instructions_icon_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/instructions.png"))); // NOI18N
        instructions_icon_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructions_icon_jLabelMouseClicked(evt);
            }
        });
        home_UI_jPanel.add(instructions_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 88, -1, -1));

        instructions_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instructions_title_jLabel.setText("Instructions");
        home_UI_jPanel.add(instructions_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 170, -1, -1));
        home_UI_jPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));
        home_UI_jPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 190, 140, -1));

        credits_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        credits_title_jLabel.setText("Credits");
        home_UI_jPanel.add(credits_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));
        home_UI_jPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 190, 140, -1));

        credits_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        credits_description_jLabel.setText("<html><center>Credits given to those<br>who made Order Tracker<br>possible.</html>");
        credits_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(credits_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        instructions_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_description_jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instructions_description_jLabel.setText("<html><center>Clear instrustions on how<br>to use Order Tracker.</html>");
        instructions_description_jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home_UI_jPanel.add(instructions_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        home_UI_jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 240));

        UI_jPanel.add(home_UI_jPanel, "card2");

        complete_order_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        complete_order_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complete_order_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jLabel.setText("Customer's Name:");
        complete_order_UI_jPanel.add(complete_order_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        complete_order_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_CN_jTextField.setBorder(null);
        complete_order_CN_jTextField.setOpaque(false);
        complete_order_CN_jTextField.setBackground(new Color(0,0,0,0));
        complete_order_CN_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_order_CN_jTextFieldActionPerformed(evt);
            }
        });
        complete_order_UI_jPanel.add(complete_order_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 340, 30));
        complete_order_UI_jPanel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 340, -1));

        complete_order_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        complete_order_TS_jLabel.setText("Time Slot:");
        complete_order_UI_jPanel.add(complete_order_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        complete_order_TS_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        complete_order_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30  PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        complete_order_UI_jPanel.add(complete_order_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("<html>Need help finding a customer's name?<br>Search by time slot!</html>");
        complete_order_UI_jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        complete_order_submit_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        complete_order_UI_jPanel.add(complete_order_submit_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(complete_order_UI_jPanel, "card2");

        calendar_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        calendar_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calendar_TT_jLabel.setText("Today/Tomorrow:");
        calendar_UI_jPanel.add(calendar_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        calendar_TT_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        calendar_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        calendar_UI_jPanel.add(calendar_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 170, -1));

        calendar_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00 AM", null, null, null},
                {"8:30 AM", null, null, null},
                {"9:00 AM", null, null, null},
                {"9:30 AM", null, null, null},
                {"10:00 AM", null, null, null},
                {"10:30 AM", null, null, null},
                {"11:00 AM", null, null, null},
                {"11:30 AM", null, null, null},
                {"12:00 PM", null, null, null},
                {"12:30 PM", null, null, null},
                {"1:00 PM", null, null, null},
                {"1:30 PM", null, null, null},
                {"2:00 PM", null, null, null},
                {"2:30 PM", null, null, null},
                {"3:00 PM", null, null, null},
                {"3:30 PM", null, null, null},
                {"4:00 PM", null, null, null},
                {"4:30 PM", null, null, null},
                {"5:00 PM", null, null, null},
                {"5:30 PM", null, null, null},
                {"6:00 PM", null, null, null},
                {"6:30 PM", null, null, null},
                {"7:00 PM", null, null, null},
                {"7:30 PM", null, null, null},
                {"8:00 PM", null, null, null},
                {"8:30 PM", null, null, null}
            },
            new String [] {
                "Time Slot", "Customer Name", "Customer Name", "Customer Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        calendar_jTable.getTableHeader().setResizingAllowed(false);
        calendar_jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(calendar_jTable);

        calendar_UI_jPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 850, 210));

        UI_jPanel.add(calendar_UI_jPanel, "card2");

        share_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        share_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        share_body_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        share_body_title_jLabel.setText("This must be done if Order Tracker is kept open.");
        share_UI_jPanel.add(share_body_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        share_body_description_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        share_body_description_jLabel.setText("<html>Order Tracker saves time slot data when the window is closed. If Order Tracker is not closed,<br>then time slot data will not be saved nor be shared. Share will save all time slot data and share it with<br>other local Order Tracker's on the fly!");
        share_UI_jPanel.add(share_body_description_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        share_submit_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        share_UI_jPanel.add(share_submit_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(share_UI_jPanel, "card2");

        instructions_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_howto_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_howto_jLabel.setText("How to:");
        instructions_UI_jPanel.add(instructions_howto_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        instructions_questions_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        instructions_questions_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "How do I add a customer's name to a specific time slot?", "How do I remove completed orders from a time slot?", "How do I view all time slot data?", "How do I share all time slot data with other local Order Trackers?", "What do I do if I don't know the customer's name and I want to complete their order?", "Why doesn't Order Tracker let me add more than three orders in each hour increment?" }));
        instructions_questions_jComboBox.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent event) {
                if (event.getStateChange() == ItemEvent.SELECTED) {
                    Object item = event.getItem();

                    if (item.toString().equals("How do I add a customer's name to a specific time slot?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_add_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I remove completed orders from a time slot?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_complete_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I view all time slot data?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_view_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("How do I share all time slot data with other local Order Trackers?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_share_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("What do I do if I don't know the customer's name and I want to complete their order?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_dkcn_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                    else if (item.toString().equals("Why doesn't Order Tracker let me add more than three orders in each hour increment?")) {
                        instructions_body_jPanel.removeAll();
                        instructions_body_jPanel.add(instructions_max_jPanel);
                        instructions_body_jPanel.repaint();
                        instructions_body_jPanel.revalidate();
                    }
                }
            }
        });
        instructions_questions_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructions_questions_jComboBoxActionPerformed(evt);
            }
        });
        instructions_UI_jPanel.add(instructions_questions_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 530, -1));

        instructions_body_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_body_jPanel.setLayout(new java.awt.CardLayout());

        instructions_add_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_add_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel.setText("How do I add a customer's name to a specific time slot?");
        instructions_add_jPanel.add(instructions_body_question_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel.setText("<html>Click the Add Customer icon on the toolbar. This will bring you to the add customer page. Fill in<br>\nthe customer's name and choose whether you would like to add their name to today's time slots or<br>\ntomorrow's time slots. Once decided, choose the time slot you and the customer agreed on for pick-up.<br>\nAfter all information is filled out, click the green checkmark button to submit your addition.</html>");
        instructions_add_jPanel.add(instructions_body_answer_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_add_user_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_user.PNG"))); // NOI18N
        instructions_add_jPanel.add(instructions_add_user_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_add_jPanel, "card2");

        instructions_complete_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_complete_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel2.setText("How do I remove completed orders from a time slot?");
        instructions_complete_jPanel.add(instructions_body_question_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel2.setText("<html>\nWhen an order is completed, click the Complete Order button in the toolbar. This will bring you to the<br>\nComplete Order page. If you know the customer's name, fill in the name in the designated area. If you<br>\ndo not know the customer's name, you can search for the customer's name with a given time slot. This<br>\nwill display all customer's name on that specific time slot to help you when searching. Once the customer's<br>\nname is filled in, press the green button with the checkmark to submit your completion.\n</html>");
        instructions_complete_jPanel.add(instructions_body_answer_jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_complete_order_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/complete_order.PNG"))); // NOI18N
        instructions_complete_jPanel.add(instructions_complete_order_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_complete_jPanel, "card2");

        instructions_view_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_view_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel3.setText("How do I view all time slot data?");
        instructions_view_jPanel.add(instructions_body_question_jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel3.setText("<html>\nTo view time slot data, click the View Time Slots button. This will take you to a page with a table with<br>\ntime slot data. To view today's time slots, select Today from the choice box, vice versa to view tomorrow's<br>\ntime slot data.\n</html>");
        instructions_view_jPanel.add(instructions_body_answer_jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_view_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view_time_slots.PNG"))); // NOI18N
        instructions_view_jPanel.add(instructions_view_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_view_jPanel, "card2");

        instructions_share_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_share_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel4.setText("How do I share all time slot data with other local Order Trackers?");
        instructions_share_jPanel.add(instructions_body_question_jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel4.setText("<html>\nThere are two ways to share time slot data to other local Order Trackers. The first being the 'X' close<br>\nbutton in the top right corner like a normal window. The second way is manually through the Share button<br>\nin the toolbar. Press the green chechmark to share manually. The reason for the second option is if it is<br>\ndesired for Order Tracker to remain open. If Order Tracker is never closed, time slot data will not be shared,<br>\nhence why the second option exists.\n</html>");
        instructions_share_jPanel.add(instructions_body_answer_jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_share_icon_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/share.PNG"))); // NOI18N
        instructions_share_jPanel.add(instructions_share_icon_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        instructions_body_jPanel.add(instructions_share_jPanel, "card2");

        instructions_dkcn_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_dkcn_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel5.setText("What do I do if I don't know the customer's name and I want to complete their order?");
        instructions_dkcn_jPanel.add(instructions_body_question_jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel5.setText("<html>\n If you do not know the customer's name, you can search for the customer's name with a given time slot. To do<br>\nthis, first click the Complete Order button in the toolbar. Once there, you will be present with the option to search<br>\nby time slot. Choose the time slot you are looking for which will display all customer's name on that specific time slot<br>\nto help you when searching. Once the customer's name is filled in, press the green button with the checkmark to<br>\nsubmit your completion.\n</html>");
        instructions_dkcn_jPanel.add(instructions_body_answer_jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_body_jPanel.add(instructions_dkcn_jPanel, "card2");

        instructions_max_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        instructions_max_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instructions_body_question_jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instructions_body_question_jLabel6.setText("Why doesn't Order Tracker let me add more than three orders in each hour increment?");
        instructions_max_jPanel.add(instructions_body_question_jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        instructions_body_answer_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructions_body_answer_jLabel6.setText("<html>\nOrder Tracker will only allow a maximum of three orders for each hour increment. This is due to the fact that<br>\noverbooking is an easy and quick way to overburden you and your coworkers in the Copy & Print Center. Order<br>\nTracker will attempt to minimize the amount of overbooking done by giving a maximum to the amount of orders that<br>\nare allowed to be taken in a given hour.\n</html>");
        instructions_max_jPanel.add(instructions_body_answer_jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        instructions_body_jPanel.add(instructions_max_jPanel, "card2");

        instructions_UI_jPanel.add(instructions_body_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 850, 190));

        UI_jPanel.add(instructions_UI_jPanel, "card2");

        credits_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        credits_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        credits_body_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        credits_body_title_jLabel.setText("Thank you to all who made Order Tracker possible!");
        credits_UI_jPanel.add(credits_body_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        credits_jTextArea.setEditable(false);
        credits_jTextArea.setBackground(new java.awt.Color(185, 185, 185));
        credits_jTextArea.setColumns(20);
        credits_jTextArea.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credits_jTextArea.setRows(5);
        credits_jTextArea.setText("Developed by Jori El-Saikali.\n\nA special thanks to all the staff at store 16! Without them I would have never created Order Tracker. Thank you all!\n\nResource Credits:\n\nHouse black silhouette without door icon made by Freepik from www.flaticon.com\nNew user free icon made by Freepik from www.flaticon.com\nChecked free icon made by Smashicons from www.flaticon.com\nCalendar free icon made by Smashicons from www.flaticon.com\nLocal network free icon made by Nikita Golubev from www.flaticon.com\nSearch free icon made by Smashicons from www.flaticon.com\nThumbs up free icon made by Dave Gandy from www.flaticon.com\nInstructions free icon made by Smashicons from www.flaticon.com\nVerified notes symbol free icon made by Freepik from www.flaticon.com");
        credits_jTextArea.setCaretPosition(0);
        jScrollPane1.setViewportView(credits_jTextArea);

        credits_UI_jPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 860, 190));

        UI_jPanel.add(credits_UI_jPanel, "card2");

        search_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        search_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_body_title_jLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_body_title_jLabel.setText("Results");
        search_UI_jPanel.add(search_body_title_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        search_results_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        search_results_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        search_UI_jPanel.add(search_results_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 870, 190));

        UI_jPanel.add(search_UI_jPanel, "card2");

        add_user_UI_jPanel.setBackground(new java.awt.Color(192, 192, 192));
        add_user_UI_jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_user_TS_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TS_jLabel.setText("Time Slot:");
        add_user_UI_jPanel.add(add_user_TS_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 178, -1, -1));

        add_user_CN_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jLabel.setText("Customer's Name:");
        add_user_UI_jPanel.add(add_user_CN_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        add_user_TT_jLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_TT_jLabel.setText("Today/Tomorrow:");
        add_user_UI_jPanel.add(add_user_TT_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 128, -1, -1));

        add_user_CN_jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_user_CN_jTextField.setBorder(null);
        add_user_CN_jTextField.setOpaque(false);
        add_user_CN_jTextField.setBackground(new Color(0,0,0,0));

        add_user_CN_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_CN_jTextFieldActionPerformed(evt);
            }
        });
        add_user_UI_jPanel.add(add_user_CN_jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 66, 340, 30));
        add_user_UI_jPanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 96, 340, -1));

        add_user_TT_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_user_TT_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Tomorrow" }));
        add_user_UI_jPanel.add(add_user_TT_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 170, -1));

        add_user_TS_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add_user_TS_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30  PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM" }));
        add_user_UI_jPanel.add(add_user_TS_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, -1));

        add_user_submit_jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/227930-P1XP19-38 - Copy_1.png"))); // NOI18N
        add_user_submit_jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_user_submit_jLabelMouseClicked(evt);
            }
        });
        add_user_UI_jPanel.add(add_user_submit_jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, 80, 80));

        UI_jPanel.add(add_user_UI_jPanel, "card2");

        getContentPane().add(UI_jPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 970, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(home_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(home_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_home_jLabelMouseClicked

    private void add_user_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_user_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(add_user_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(add_user_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_add_user_jLabelMouseClicked

    private void complete_order_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complete_order_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(complete_order_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(complete_order_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_complete_order_jLabelMouseClicked

    private void calendar_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendar_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(calendar_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(calendar_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_calendar_jLabelMouseClicked

    private void share_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_share_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(share_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(share_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_share_jLabelMouseClicked

    private void add_user_CN_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_CN_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_user_CN_jTextFieldActionPerformed

    private void complete_order_CN_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_order_CN_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complete_order_CN_jTextFieldActionPerformed

    private void instructions_questions_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructions_questions_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructions_questions_jComboBoxActionPerformed

    private void instructions_icon_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructions_icon_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(instructions_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(instructions_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_instructions_icon_jLabelMouseClicked

    private void thumbs_up_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thumbs_up_jLabelMouseClicked
        UI_jPanel.removeAll();
        UI_jPanel.add(credits_UI_jPanel);
        UI_jPanel.repaint();
        UI_jPanel.revalidate();
        
        title_jPanel.removeAll();
        title_jPanel.add(credits_title_jPanel);
        title_jPanel.repaint();
        title_jPanel.revalidate();
    }//GEN-LAST:event_thumbs_up_jLabelMouseClicked

    private void search_jTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_jTextFieldKeyPressed
       if (evt.getKeyCode() == 10) {
           // Search
           UI_jPanel.removeAll();
           UI_jPanel.add(search_UI_jPanel);
           UI_jPanel.repaint();
           UI_jPanel.revalidate();

           title_jPanel.removeAll();
           title_jPanel.add(search_title_jPanel);
           title_jPanel.repaint();
           title_jPanel.revalidate();
       }
    }//GEN-LAST:event_search_jTextFieldKeyPressed

    private void add_user_submit_jLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_user_submit_jLabelMouseClicked
        System.out.println("pressed");
        action = "add_user_submit";
        System.out.println(action);
    }//GEN-LAST:event_add_user_submit_jLabelMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public void RunGFX() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
    public void AddLinkToResults() {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UI_jPanel;
    private javax.swing.JLabel add_user_CN_jLabel;
    private javax.swing.JTextField add_user_CN_jTextField;
    private javax.swing.JComboBox<String> add_user_TS_jComboBox;
    private javax.swing.JLabel add_user_TS_jLabel;
    private javax.swing.JComboBox<String> add_user_TT_jComboBox;
    private javax.swing.JLabel add_user_TT_jLabel;
    private javax.swing.JPanel add_user_UI_jPanel;
    private javax.swing.JLabel add_user_jLabel;
    private javax.swing.JLabel add_user_submit_jLabel;
    private javax.swing.JLabel add_user_subtitle_jLabel;
    private javax.swing.JLabel add_user_title_jLabel;
    private javax.swing.JPanel add_user_title_jPanel;
    private javax.swing.JComboBox<String> calendar_TT_jComboBox;
    private javax.swing.JLabel calendar_TT_jLabel;
    private javax.swing.JPanel calendar_UI_jPanel;
    private javax.swing.JLabel calendar_jLabel;
    private javax.swing.JTable calendar_jTable;
    private javax.swing.JLabel calendar_subtitle_jLabel;
    private javax.swing.JLabel calendar_title_jLabel;
    private javax.swing.JPanel calendar_title_jPanel;
    private javax.swing.JLabel complete_order_CN_jLabel;
    private javax.swing.JTextField complete_order_CN_jTextField;
    private javax.swing.JComboBox<String> complete_order_TS_jComboBox;
    private javax.swing.JLabel complete_order_TS_jLabel;
    private javax.swing.JPanel complete_order_UI_jPanel;
    private javax.swing.JLabel complete_order_jLabel;
    private javax.swing.JLabel complete_order_submit_jLabel;
    private javax.swing.JLabel complete_order_subtitle_jLabel1;
    private javax.swing.JLabel complete_order_title_jLabel1;
    private javax.swing.JPanel complete_order_title_jPanel;
    private javax.swing.JPanel credits_UI_jPanel;
    private javax.swing.JLabel credits_body_title_jLabel;
    private javax.swing.JLabel credits_description_jLabel;
    private javax.swing.JTextArea credits_jTextArea;
    private javax.swing.JLabel credits_main_title_jLabel;
    private javax.swing.JLabel credits_subtitle_jLabel;
    private javax.swing.JLabel credits_title_jLabel;
    private javax.swing.JPanel credits_title_jPanel;
    private javax.swing.JPanel home_UI_jPanel;
    private javax.swing.JLabel home_jLabel;
    private javax.swing.JPanel home_title_jPanel;
    private javax.swing.JPanel instructions_UI_jPanel;
    private javax.swing.JPanel instructions_add_jPanel;
    private javax.swing.JLabel instructions_add_user_icon_jLabel;
    private javax.swing.JLabel instructions_body_answer_jLabel;
    private javax.swing.JLabel instructions_body_answer_jLabel2;
    private javax.swing.JLabel instructions_body_answer_jLabel3;
    private javax.swing.JLabel instructions_body_answer_jLabel4;
    private javax.swing.JLabel instructions_body_answer_jLabel5;
    private javax.swing.JLabel instructions_body_answer_jLabel6;
    private javax.swing.JPanel instructions_body_jPanel;
    private javax.swing.JLabel instructions_body_question_jLabel;
    private javax.swing.JLabel instructions_body_question_jLabel2;
    private javax.swing.JLabel instructions_body_question_jLabel3;
    private javax.swing.JLabel instructions_body_question_jLabel4;
    private javax.swing.JLabel instructions_body_question_jLabel5;
    private javax.swing.JLabel instructions_body_question_jLabel6;
    private javax.swing.JPanel instructions_complete_jPanel;
    private javax.swing.JLabel instructions_complete_order_icon_jLabel;
    private javax.swing.JLabel instructions_description_jLabel;
    private javax.swing.JPanel instructions_dkcn_jPanel;
    private javax.swing.JLabel instructions_howto_jLabel;
    private javax.swing.JLabel instructions_icon_jLabel;
    private javax.swing.JLabel instructions_main_title_jLabel;
    private javax.swing.JPanel instructions_max_jPanel;
    private javax.swing.JComboBox<String> instructions_questions_jComboBox;
    private javax.swing.JLabel instructions_share_icon_jLabel;
    private javax.swing.JPanel instructions_share_jPanel;
    private javax.swing.JLabel instructions_subtitle_jLabel;
    private javax.swing.JLabel instructions_title_jLabel;
    private javax.swing.JPanel instructions_title_jPanel;
    private javax.swing.JLabel instructions_view_icon_jLabel;
    private javax.swing.JPanel instructions_view_jPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel order_tracker_jLabel;
    private javax.swing.JPanel search_UI_jPanel;
    private javax.swing.JPanel search_area_jPanel;
    private javax.swing.JLabel search_body_title_jLabel;
    private javax.swing.JLabel search_icon_jLabel;
    private javax.swing.JTextField search_jTextField;
    private javax.swing.JLabel search_main_title_jLabel;
    private javax.swing.JPanel search_results_jPanel;
    private javax.swing.JLabel search_subtitle_jLabel;
    private javax.swing.JPanel search_title_jPanel;
    private javax.swing.JPanel share_UI_jPanel;
    private javax.swing.JLabel share_body_description_jLabel;
    private javax.swing.JLabel share_body_title_jLabel;
    private javax.swing.JLabel share_jLabel;
    private javax.swing.JLabel share_submit_jLabel;
    private javax.swing.JLabel share_subtitle_jLabel;
    private javax.swing.JLabel share_title_jLabel;
    private javax.swing.JPanel share_title_jPanel;
    private javax.swing.JLabel staples_logo_jLabel;
    private javax.swing.JLabel thumbs_up_jLabel;
    private javax.swing.JPanel title_jPanel;
    private javax.swing.JPanel toolbar_blank_jPanel;
    private javax.swing.JPanel toolbar_jPanel;
    private javax.swing.JLabel welcome_jLabel;
    // End of variables declaration//GEN-END:variables
}
